. "C:\Users\gianl\OneDrive\Desktop\AI\fixhive\gen-brands.ps1"

$base = "C:\Users\gianl\OneDrive\Desktop\AI\fixhive"

$brands2 = @(

@{ slug="cadillac"; name="Cadillac"; nameAr="كاديلاك"
   title="Cadillac Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Cadillac repair in Dubai. Escalade, CT5, XT5, XT6 &amp; CT4 specialists. V8 engine, Magnetic Ride Control &amp; Super Cruise servicing. FixHive Dubai."
   models="Escalade · CT5 · CT4 · XT5 · XT6 · Lyriq"
   heroSub="Dubai specialists for Cadillac Escalade, CT5, XT5 and XT6 — 6.2L V8, Magnetic Ride Control suspension, Super Cruise ADAS and Bose audio system care."
   intro1="Cadillac has a long-standing presence in Dubai and the broader GCC market, where the Escalade in particular holds an almost iconic status as the premium large SUV of choice for business and government fleets. The current generation Escalade, with its spectacular 38-inch curved OLED instrument cluster, 6.2-litre naturally aspirated V8 and air suspension, represents the absolute pinnacle of American luxury — and its service requirements match its sophistication."
   intro2="The 6.2-litre L87 V8 in the Escalade and CT5-V uses Active Fuel Management (AFM) cylinder deactivation, which can cause oil consumption and lifter noise issues if the dedicated AFM oil pressure isn't maintained. Cadillac specifies dexos1 Gen 3 full synthetic 0W-20 oil; substitution with other viscosities will cause the AFM system to behave incorrectly in Dubai's heat. The CT5 and CT4 use a 2.0-litre turbocharged four-cylinder — a robust engine but one that requires clean air filtration given Dubai's dusty environment."
   intro3="Magnetic Ride Control suspension, fitted to CT5-V and optionally to other models, uses magnetorheological fluid in the dampers and adjusts damper stiffness 1,000 times per second based on road input. In Dubai, where speed bumps are frequent and road surfaces can change abruptly, MRC dampers cycle more aggressively than in their designed climate. We service and replace Magnetic Ride Control units and carry out the associated calibration. FixHive also handles Super Cruise ADAS calibration following any windscreen work or front-end repair."
   i1h="L87 V8 Lifter Failures from AFM System"
   i1p="The Active Fuel Management system in the 6.2-litre V8 uses hydraulic lifters that collapse when cylinders deactivate. In Dubai's heat, if oil changes are delayed or incorrect oil viscosity is used, the AFM lifter passages can develop sludge that causes the lifters to stick in their collapsed position. This produces a distinctive ticking noise from the engine and a misfire condition. Left unaddressed, failed lifters can cause camshaft and pushrod damage. Prevention is straightforward: use Cadillac-specified dexos1 0W-20 and change oil every 8,000 km in Dubai rather than the Oil Life Monitor recommendation."
   i2h="Air Suspension Compressor Failures on Escalade"
   i2p="The Escalade's air suspension provides the supple, level ride expected of a luxury SUV, but the air compressor is a known weak point on high-mileage examples. Dubai's high ambient temperatures cause the compressor to cycle more frequently, and the intake air filter — which prevents dust from entering the system — degrades faster in the UAE's dusty environment. A failing compressor typically presents as a slow levelling-up after parking, a groaning sound from the rear when the car settles, and eventually a SERVICE RIDE CONTROL message. We carry Escalade air compressor units in stock."
   i3h="Magnetic Ride Control Damper Wear"
   i3p="Magnetic Ride Control dampers on CT5-V have a service life that is significantly shortened by UAE conditions. The frequency and severity of speed bumps on Dubai and Abu Dhabi roads — combined with the additional cycling caused by thermal expansion of the MR fluid — accelerates damper wear compared to the US market. Symptoms of worn MRC dampers include a loss of the characteristic comfortable-yet-controlled ride, increased body roll in corners and a harder-than-expected impact over sharp bumps. We use OEM Delphi MRC units for all replacements and perform the mandatory module adaptation after fitting."
   i4h="Infotainment OLED Screen Failures"
   i4p="The Escalade's 38-inch curved OLED display is a landmark piece of automotive technology, but OLED panels are more sensitive to prolonged heat exposure than conventional LCD screens. UAE-registered Escalades left in direct sunlight for extended periods during summer can experience premature pixel degradation, particularly in areas of the screen that display static content (like navigation icons). We recommend using the automatic sunshade and parking in shade wherever possible. We also perform the GM software update that reduces screen brightness when ambient temperature exceeds 45°C, which was introduced as a field fix for early OLED degradation."
   faq1q="How much does Cadillac Escalade servicing cost in Dubai?"
   faq1a="Annual Escalade services at FixHive covering oil and filter change, dexos1 top-up check, multi-point inspection and tyre rotation start from AED 600–900. Major services including air suspension inspection, brake fluid replacement and full drivetrain fluid service range from AED 1,200–2,000 depending on the model year."
   faq2q="What oil should I use in my Cadillac in Dubai?"
   faq2a="All Cadillac V8 models require dexos1 Gen 3 certified full synthetic 0W-20 oil. This specification is mandatory for correct AFM and VVT operation. Do not use 5W-30 or any other viscosity unless specifically instructed by a Cadillac-authorised diagnostic — the AFM system calibration depends on 0W-20 viscosity at operating temperature."
   faq3q="How often should I service my Cadillac in Dubai?"
   faq3a="We recommend oil changes every 8,000 km or annually in Dubai, rather than following the Oil Life Monitor alone. The UAE's heat cycles degrade oil faster than the OLM algorithm accounts for. Air filter replacement every 15,000 km is also advisable given Dubai's dust."
   faq4q="Can FixHive calibrate Super Cruise after a windscreen replacement?"
   faq4a="Yes. Super Cruise uses a forward-facing camera mounted at the top of the windscreen. After any windscreen replacement, the camera must be statically calibrated using manufacturer targets. We hold the GM ADAS calibration software and targets for all current Cadillac platforms."
   faq5q="What are common problems with the Cadillac Escalade in UAE?"
   faq5a="Air suspension compressor failures (especially on 2015-2020 models), AFM lifter noise on V8 engines and occasional OLED screen brightness issues are the most common items we see on UAE Escalades. All are preventable with correct servicing intervals and quality fluids."
   ctaSub="Escalade V8, Magnetic Ride Control and OLED infotainment care — American luxury serviced right in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Cadillac%20service"
   relatedEn='<a href="chevrolet-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Chevrolet</a><a href="gmc-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">GMC</a><a href="ford-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Ford</a><a href="land-rover-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Land Rover</a><a href="mercedes-benz-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Mercedes-Benz</a>'
   titleAr="إصلاح كاديلاك في دبي | Escalade، CT5، XT5 | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة كاديلاك في دبي. Escalade وCT5 وXT5 وXT6. محرك V8 وتعليق Magnetic Ride Control. فيكس هايف دبي."
   heroSubAr="متخصصون في كاديلاك Escalade وCT5 وXT5 وXT6 — محرك V8، تعليق Magnetic Ride Control ونظام Super Cruise."
   intro1Ar="كاديلاك حضور راسخ في دبي ودول الخليج، حيث يحتفظ Escalade بمكانة أيقونية بوصفه السيارة الفاخرة الكبيرة المفضلة للأساطيل التجارية والحكومية. الجيل الحالي من Escalade بشاشة OLED المنحنية بعرض 38 بوصة ومحرك V8 6.2 لتر وتعليقه الهوائي يمثل قمة الفخامة الأمريكية."
   intro2Ar="محرك L87 V8 في Escalade وCT5-V يستخدم نظام AFM لإيقاف تشغيل أسطوانات. كاديلاك تحدد زيت dexos1 Gen 3 تخليقي كامل 0W-20؛ استخدام لزوجات أخرى يُعطّل نظام AFM في حرارة دبي."
   intro3Ar="تعليق Magnetic Ride Control المُثبَّت في CT5-V يستخدم سائلاً ريولوجياً مغناطيسياً يضبط صلابة المخمدات 1,000 مرة في الثانية. في دبي حيث المطبات متكررة وسطح الطريق يتغير فجأة، تعمل مخمدات MRC بشكل أكثر شدة مما يُسرّع التآكل."
   i1hAr="أعطال رافعات L87 V8 من نظام AFM"
   i1pAr="إذا تأخر تغيير الزيت أو استُخدم زيت بلزوجة خاطئة، يمكن أن تتراكم الترسبات في ممرات رافعات AFM وتتعطل. يُنتج هذا صوت طرق مميزاً من المحرك. الوقاية بسيطة: استخدام dexos1 0W-20 وتغيير الزيت كل 8,000 كم في دبي."
   i2hAr="أعطال ضاغط التعليق الهوائي في Escalade"
   i2pAr="يعاني ضاغط تعليق Escalade الهوائي من أعطال متكررة في الأمثلة عالية الكيلومترات. حرارة دبي المرتفعة تزيد من دورات الضاغط، كما يتدهور فلتر الهواء في بيئة الإمارات الغبارية بشكل أسرع."
   i3hAr="تآكل مخمدات Magnetic Ride Control"
   i3pAr="مطبات دبي المتكررة وتمدد سائل MR الحراري يُسرّعان تآكل المخمدات. الأعراض تشمل فقدان الراحة المميزة وزيادة التمايل في المنعطفات."
   i4hAr="أعطال شاشة OLED للمعلومات والترفيه"
   i4pAr="شاشة OLED المنحنية في Escalade أكثر حساسية للحرارة المطولة من شاشات LCD. نوصي باستخدام الستارة الشمسية والوقوف في الظل. نجري أيضاً تحديث البرنامج الذي يُخفّض سطوع الشاشة عند 45°C+."
   faq1qAr="كم تكلفة صيانة كاديلاك Escalade في دبي؟"
   faq1aAr="الصيانة السنوية من 600–900 درهم. الصيانة الشاملة من 1,200–2,000 درهم حسب الموديل."
   faq2qAr="ما الزيت الموصى به لكاديلاك في دبي؟"
   faq2aAr="جميع موديلات كاديلاك V8 تتطلب dexos1 Gen 3 تخليقي كامل 0W-20. لا تستبدل بـ 5W-30 أو أي لزوجة أخرى."
   faq3qAr="كم مرة يجب تغيير زيت كاديلاك في دبي؟"
   faq3aAr="نوصي بتغيير الزيت كل 8,000 كم سنوياً في دبي. حرارة الإمارات تُسرّع تدهور الزيت أسرع مما يحسبه مؤشر عمر الزيت."
   faq4qAr="هل تستطيع فيكس هايف معايرة Super Cruise بعد استبدال الزجاج الأمامي؟"
   faq4aAr="نعم. نمتلك برنامج معايرة ADAS من GM وأهداف المعايرة لجميع منصات كاديلاك الحالية."
   faq5qAr="ما أكثر أعطال كاديلاك Escalade شيوعاً في الإمارات؟"
   faq5aAr="أعطال ضاغط التعليق الهوائي وصوت رافعات V8 ومشكلات سطوع شاشة OLED من أكثر ما نراه في Escalade الإماراتية."
   ctaSubAr="رعاية V8 وMagnetic Ride Control وشاشة OLED — الفخامة الأمريكية تُصان بشكل صحيح في دبي."
},

@{ slug="changan"; name="Changan"; nameAr="شانجان"
   title="Changan Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Changan repair in Dubai. CS75 Plus, CS35 Plus, Uni-T, Uni-K, Lamore &amp; Alsvin specialists. Engine, gearbox &amp; ADAS servicing. FixHive Dubai."
   models="CS75 Plus · CS35 Plus · Uni-T · Uni-K · Lamore · Alsvin · Hunter"
   heroSub="Dubai specialists for Changan CS75, Uni-T, Uni-K and Lamore — turbocharged engine, DCT gearbox, ADAS calibration and all-climate servicing."
   intro1="Changan has emerged as one of the most competitive Chinese automotive brands in the UAE market, combining modern design, feature-rich specifications and competitive pricing that has attracted a significant owner base in Dubai and across the Emirates. The CS75 Plus and Uni-T are among the most frequently encountered Chinese SUVs on UAE roads, while the newer Uni-K and Lamore models have raised the brand's profile in the premium segment. As the Changan fleet grows, so does the demand for independent service specialists who understand the specific requirements of these vehicles."
   intro2="Changan's current generation uses turbocharged four-cylinder petrol engines — principally the 1.5T and 2.0T TGDI units — paired with either conventional torque converter automatics or Dual Clutch Transmissions (DCT). The 2.0T engine is a competitive unit but requires strict adherence to oil specifications in UAE conditions; Changan recommends 5W-30 full synthetic and the engine is sensitive to oil quality in high ambient temperatures. The DCT gearbox, fitted to many CS75 and Uni-series models, requires its own specific transmission fluid that must be replaced every 60,000 km to prevent the clutch pack wear that is DCTs' Achilles heel in stop-start urban traffic."
   intro3="Changan's ADAS suite on current models is notably comprehensive for the price point, including forward collision warning, automatic emergency braking, blind spot monitoring and a 360-degree camera system. All these systems require periodic calibration, particularly after any windscreen work or front-end repair. FixHive provides the full range of Changan mechanical and electronic service, with diagnostic tools that cover the complete fault code range and adaptation functions for Changan's engine management and gearbox control systems."
   i1h="DCT Gearbox Judder in Dubai Stop-Start Traffic"
   i1p="Changan's Dual Clutch Transmission is well-suited to motorway driving but faces its most demanding conditions in Dubai's stop-start urban traffic, where the wet clutch packs engage and disengage at very low speeds hundreds of times per hour. In temperatures above 40°C, the clutch fluid in the DCT sump degrades faster, increasing clutch-to-clutch friction and causing a judder or hesitation when pulling away from standstill. The DCT fluid must be replaced every 60,000 km; in heavy city driving we recommend every 40,000 km. We also carry out the DCT clutch adaptation procedure after fluid replacement to reset the clutch engagement point."
   i2h="2.0T TGDI Engine Overheating Under Sustained Load"
   i2p="The 2.0-litre TGDI turbocharged engine in higher-specification CS75 Plus and Uni-K models produces strong performance but generates significant heat under sustained high-load conditions. In UAE summers, driving at highway speeds with full AC load can push coolant temperature to the upper limit of the normal range. The engine's low-pressure EGR system — used for emission compliance — can accumulate carbon deposits in the intake manifold over time, reducing airflow efficiency and contributing to temperature increases. We perform intake manifold cleaning and EGR system inspection at every major service."
   i3h="Air Conditioning Compressor Failures"
   i3p="Changan's Chinese-sourced air conditioning compressors are adequate for temperate climates but work at the edge of their design envelope in Dubai's 8-month summer. The compressor clutch and magnetic coil are the most frequent failure items — the clutch slips initially under the extreme load of maximum compressor operation, producing a squealing noise when AC is first switched on. Left unaddressed, a slipping clutch burns the magnetic coil and eventually seizes the compressor. We carry Changan-compatible aftermarket compressors and can complete the compressor replacement including system evacuation and recharge in a single day."
   i4h="ADAS Camera &amp; Sensor Calibration"
   i4p="Changan's Advanced Driver Assistance Systems on current models use a windscreen-mounted forward camera for lane departure and collision detection, plus ultrasonic sensors and a rear camera for the parking system. After any windscreen replacement or front-end panel repair, the forward camera requires static calibration at a specific distance from calibration targets. The rear parking sensors require gap verification after any rear bumper work. FixHive has invested in the Changan-compatible calibration equipment and software to complete all ADAS procedures correctly."
   faq1q="How much does Changan servicing cost in Dubai?"
   faq1a="Minor Changan services at FixHive start from AED 300–450, covering oil and filter change, multi-point inspection and fluid top-ups. Major services every 30,000 km including DCT fluid, air filter, spark plugs and brake inspection range from AED 600–900."
   faq2q="How often should I change DCT fluid on a Changan?"
   faq2a="Every 40,000–60,000 km in Dubai conditions. DCT gearboxes are more sensitive to fluid condition than conventional automatics, and Dubai's heat and stop-start traffic accelerate fluid degradation. Never use universal ATF in a Changan DCT — always use the specified Changan DCT fluid."
   faq3q="Is the Changan 2.0T engine reliable in Dubai heat?"
   faq3a="Yes, with correct servicing. The 2.0T TGDI engine is a well-engineered unit, but it requires quality 5W-30 full synthetic oil changed every 7,500–10,000 km in UAE conditions, and the air filter must be inspected more frequently than in cooler climates due to Dubai's dust. The intake manifold benefits from a carbon cleaning service every 60,000 km."
   faq4q="Does FixHive have diagnostic tools for Changan?"
   faq4a="Yes. We use diagnostic software covering all current Changan models sold in the UAE, including full fault code access, live data streams and adaptation functions for the engine management, DCT gearbox, ABS and ADAS systems."
   faq5q="What is the recommended service interval for Changan in the UAE?"
   faq5a="We recommend oil changes every 7,500–10,000 km, air filter inspection every 15,000 km, and a full major service every 30,000 km covering spark plugs, DCT fluid (if applicable), brake fluid and a comprehensive brake and suspension inspection."
   ctaSub="Changan 1.5T and 2.0T engine care, DCT servicing and ADAS calibration — quality independent service in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Changan%20service"
   relatedEn='<a href="chery-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Chery</a><a href="haval-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Haval</a><a href="mg-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">MG</a><a href="geely-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Geely</a><a href="toyota-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Toyota</a>'
   titleAr="إصلاح شانجان في دبي | CS75، Uni-T، Uni-K | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة شانجان في دبي. CS75 Plus وCS35 وUni-T وUni-K ولامور. محرك توربو وناقل DCT ومعايرة ADAS."
   heroSubAr="متخصصون في شانجان CS75 وUni-T وUni-K ولامور — محرك توربو وناقل DCT ومعايرة ADAS في جميع الظروف المناخية."
   intro1Ar="برزت شانجان بوصفها من أكثر العلامات الصينية تنافسية في السوق الإماراتية، إذ جمعت تصميماً عصرياً ومواصفات غنية وأسعاراً تنافسية استقطبت قاعدة عملاء واسعة في دبي وسائر الإمارات. CS75 Plus وUni-T من أكثر SUVs الصينية انتشاراً في الإمارات."
   intro2Ar="تستخدم شانجان الحالية محركات توربو 1.5T و2.0T TGDI مقترنة بناقلات تلقائية تقليدية أو ناقلات DCT ذات قابض مزدوج. محرك 2.0T وحدة تنافسية لكنها حساسة لجودة الزيت في الحرارة الشديدة. ناقل DCT في كثير من موديلات CS75 وUni يحتاج سائله الخاص كل 60,000 كم."
   intro3Ar="مجموعة ADAS في شانجان الحالية شاملة بشكل لافت للفئة السعرية. جميع هذه الأنظمة تحتاج معايرة دورية خاصة بعد أعمال الزجاج أو تصليح المقدمة. فيكس هايف تقدم خدمة ميكانيكية وإلكترونية كاملة لشانجان."
   i1hAr="اهتزاز ناقل DCT في ازدحام دبي"
   i1pAr="ناقل DCT في شانجان يواجه تحدياته الأصعب في ازدحام دبي حيث تنخرط صفائح القابض وتنفصل بسرعات منخفضة جداً مئات المرات في الساعة. سائل القابض يتدهور بشكل أسرع فوق 40°C. يجب تغيير سائل DCT كل 40,000–60,000 كم."
   i2hAr="ارتفاع حرارة محرك 2.0T في ظروف الحمل المستمر"
   i2pAr="يولّد محرك 2.0T TGDI حرارة كبيرة في ظروف الحمل المرتفع. في صيف الإمارات قد ترتفع درجة حرارة سائل التبريد إلى الحد الأعلى. رواسب الكربون في مشعب السحب تُقلّل كفاءة تدفق الهواء."
   i3hAr="أعطال ضاغط التكييف"
   i3pAr="ضواغط التكييف الصينية في شانجان تعمل عند حافة نطاق تصميمها في صيف دبي الممتد 8 أشهر. القابض والملف المغناطيسي أكثر قطع الأعطال شيوعاً."
   i4hAr="معايرة كاميرا ADAS والحساسات"
   i4pAr="تستخدم أنظمة ADAS في شانجان الحالية كاميرا أمامية مثبتة على الزجاج وحساسات فوق صوتية. بعد أي استبدال للزجاج يجب معايرة الكاميرا."
   faq1qAr="كم تكلفة صيانة شانجان في دبي؟"
   faq1aAr="تبدأ الصيانة الخفيفة من 300–450 درهم. الصيانة الشاملة كل 30,000 كم من 600–900 درهم."
   faq2qAr="كم مرة يجب تغيير سائل DCT في شانجان؟"
   faq2aAr="كل 40,000–60,000 كم في ظروف دبي. لا تستخدم سائل ATF عاماً في ناقل شانجان DCT — استخدم السائل المحدد دائماً."
   faq3qAr="هل محرك شانجان 2.0T موثوق في حرارة دبي؟"
   faq3aAr="نعم مع الصيانة الصحيحة. يتطلب زيت تخليقي 5W-30 كامل كل 7,500–10,000 كم وتنظيف مشعب السحب من الكربون كل 60,000 كم."
   faq4qAr="هل تمتلك فيكس هايف أدوات تشخيص لشانجان؟"
   faq4aAr="نعم. نستخدم برامج تشخيص تغطي جميع موديلات شانجان الحالية في الإمارات."
   faq5qAr="ما الفترة الموصى بها لصيانة شانجان في الإمارات؟"
   faq5aAr="تغيير الزيت كل 7,500–10,000 كم وفحص فلتر الهواء كل 15,000 كم وصيانة شاملة كل 30,000 كم."
   ctaSubAr="رعاية محرك 1.5T و2.0T وناقل DCT ومعايرة ADAS — خدمة مستقلة متخصصة في دبي."
},

@{ slug="chery"; name="Chery"; nameAr="شيري"
   title="Chery Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Chery repair in Dubai. Tiggo 8 Pro, Tiggo 7 Pro, Arrizo 6 Pro &amp; Tiggo 4 specialists. Turbo engine, CVT &amp; DCT servicing. FixHive Garage Dubai."
   models="Tiggo 8 Pro · Tiggo 7 Pro · Tiggo 4 Pro · Arrizo 6 Pro · Omoda 5"
   heroSub="Dubai specialists for Chery Tiggo 8, Tiggo 7, Arrizo 6 and Omoda 5 — turbocharged engine servicing, CVT and DCT gearbox care, ADAS and AC maintenance."
   intro1="Chery has established a meaningful foothold in the UAE automotive market, particularly with the Tiggo 8 Pro — a seven-seat SUV that offers premium European-influenced styling and a long feature list at a price point significantly below European and Japanese competitors. The Omoda 5 has more recently generated strong interest from younger buyers seeking a stylish crossover with modern technology at an accessible price. As Chery's UAE fleet grows, the need for skilled independent service — beyond the limited dealer network — has increased."
   intro2="Chery's current UAE lineup uses a 1.6T turbocharged petrol engine (the SQRE4T16D) in most Tiggo and Arrizo models, producing 145–197 horsepower depending on tune. This engine pairs with either a CVT (continuous variable transmission) or a 7DCT dual-clutch gearbox. The CVT variant offers smooth urban driving but requires Chery-specified CVT fluid replacement every 60,000 km — a service that is often overlooked. The 7DCT is quicker-responding but requires wet clutch pack fluid at the same interval and a clutch adaptation reset after fluid changes."
   intro3="Chery's ADAS systems on Pro models are comprehensive and well-integrated, but they require periodic alignment checks and camera calibration. The 360-degree camera system is particularly useful in Dubai's tight parking environments but requires calibration after any bumper repair or camera unit replacement. FixHive provides the complete range of Chery service, with technicians trained on all current Chery platforms and diagnostic tools that give full access to Chery's proprietary fault code architecture."
   i1h="CVT Transmission Overheating in Dubai Traffic"
   i1p="Chery's CVT-equipped Tiggo 8 and Arrizo 6 models use a belt-driven continuously variable transmission that is particularly sensitive to fluid condition in Dubai's climate. The prolonged stop-start driving that characterises Dubai city traffic keeps the CVT under near-continuous load at low belt-to-pulley speed ratios — the most thermally demanding operating condition for this type of gearbox. CVT fluid at incorrect level or beyond service life causes belt slippage, pulley wear and in extreme cases complete CVT failure. We recommend Chery CVT fluid changes every 40,000 km in UAE conditions rather than the factory 60,000 km specification."
   i2h="1.6T Engine Carbon Buildup on Intake Valves"
   i2p="Direct-injection turbocharged engines like Chery's 1.6T TGDI are prone to carbon buildup on the backs of the intake valves because fuel is injected directly into the combustion chamber rather than washing the valves as in port-injected engines. In Dubai's dusty environment this process is accelerated by air filter degradation, which allows fine particles to enter the intake path and adhere to the carbon deposits. Symptoms include rough idle, hesitation on acceleration and a minor power reduction. We offer a walnut blasting intake valve cleaning service that removes these deposits without engine disassembly."
   i3h="Air Conditioning Evaporator &amp; Compressor Issues"
   i3p="Dubai's climate demands maximum AC output for 8 months of the year, which places the Chery AC system under sustained stress. The evaporator — mounted inside the dashboard in a relatively tight space — is susceptible to mould growth in the humid UAE coastal environment when the car is parked for extended periods without the AC running the dry-out cycle. We perform an evaporator sterilisation service using ozone treatment and carry out a full refrigerant pressure test at every major service. The AC compressor belt tension is also checked at every service — a loose belt causes compressor clutch slippage and premature wear."
   i4h="Suspension &amp; Steering Wear on UAE Roads"
   i4p="UAE road surfaces, while generally well-maintained, include a significant number of speed bumps and occasional sections of rough highway surface. Chery's Tiggo 8 and Tiggo 7, despite their relatively large wheel/tyre fitments, have front lower control arm bushings and front sway bar links that wear faster in UAE conditions than in temperate markets. Symptoms include a clunking noise over speed bumps, increased steering wander and tyre wear that is uneven across the tread width. We carry Chery-compatible suspension components in stock and align all four wheels after any suspension component replacement."
   faq1q="How much does Chery servicing cost in Dubai?"
   faq1a="Minor Chery services at FixHive start from AED 280–400, covering oil and filter change, multi-point safety check and fluid level top-ups. Major services every 30,000 km including CVT or DCT fluid, air filter, spark plugs and brake inspection range from AED 550–850."
   faq2q="How often should I change CVT fluid on a Chery Tiggo in Dubai?"
   faq2a="Every 40,000 km in Dubai conditions. The factory 60,000 km recommendation is for temperate climates. Dubai's heat and stop-start traffic degrade CVT fluid faster and the consequences of fluid failure are costly — CVT replacement can exceed AED 8,000."
   faq3q="Is the Chery 1.6T engine reliable in the UAE?"
   faq3a="Generally yes, with proper maintenance. The key requirements are quality 5W-30 full synthetic oil changed every 7,500 km, clean air filtration (change filters every 15,000 km in Dubai dust), and an intake valve carbon clean every 60,000 km for direct-injection variants."
   faq4q="Does FixHive service the Chery Omoda 5?"
   faq4a="Yes. The Omoda 5 is a relatively new model but we have full diagnostic coverage. Its 1.6T engine and DCT gearbox are variants of systems used across the Tiggo lineup, so our technicians are fully familiar with the platform."
   faq5q="What are common problems with Chery vehicles in Dubai?"
   faq5a="CVT fluid degradation leading to shudder or overheating, intake valve carbon buildup on the 1.6T, AC compressor wear and front suspension bushing wear are the most frequent issues we see on UAE Chery vehicles. All are manageable with correct servicing."
   ctaSub="Chery 1.6T engine care, CVT and DCT servicing, ADAS calibration — expert independent service in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Chery%20service"
   relatedEn='<a href="changan-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Changan</a><a href="haval-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Haval</a><a href="mg-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">MG</a><a href="geely-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Geely</a><a href="toyota-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Toyota</a>'
   titleAr="إصلاح شيري في دبي | Tiggo 8، Tiggo 7، Arrizo 6 | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة شيري في دبي. Tiggo 8 Pro وTiggo 7 Pro وArrizo 6 وOmoda 5. محرك توربو وناقل CVT وDCT."
   heroSubAr="متخصصون في شيري Tiggo 8 وTiggo 7 وArrizo 6 وOmoda 5 — صيانة المحرك وناقل CVT وDCT ومعايرة ADAS."
   intro1Ar="رسّخت شيري موطئ قدم ملموساً في السوق الإماراتية، خاصة مع Tiggo 8 Pro الذي يقدم تصميماً فاخراً وقائمة مواصفات طويلة بسعر أقل بكثير من المنافسين الأوروبيين والآسيويين. Omoda 5 استقطبت اهتماماً قوياً من الشباب الباحثين عن سيارة عصرية بتقنيات حديثة."
   intro2Ar="تستخدم خط إنتاج شيري الحالي في الإمارات محرك 1.6T توربو في معظم موديلات Tiggo وArrizo، مقترناً بناقل CVT أو 7DCT ذي قابض مزدوج. ناقل CVT يتطلب سائل تغييره كل 60,000 كم — خدمة كثيراً ما تُهمل."
   intro3Ar="أنظمة ADAS في موديلات Pro شاملة ومتكاملة لكنها تتطلب فحص محاذاة دوري ومعايرة كاميرا. فيكس هايف تقدم خدمة شاملة لشيري مع أدوات تشخيص تصل إلى بنية رموز الأعطال الخاصة بالعلامة."
   i1hAr="ارتفاع حرارة ناقل CVT في ازدحام دبي"
   i1pAr="ناقل CVT في شيري Tiggo وArrizo حساس لحالة السائل في مناخ دبي. القيادة المتوقفة المستمرة تُبقي الناقل تحت حمل مستمر عند نسب سرعة منخفضة — وهو أصعب ظروف التشغيل. نوصي بتغيير سائل CVT كل 40,000 كم في الإمارات."
   i2hAr="تراكم الكربون على صمامات السحب في 1.6T"
   i2pAr="محركات الحقن المباشر كـ 1.6T TGDI عرضة لتراكم الكربون على ظهر صمامات السحب. في بيئة دبي الغبارية تتسارع هذه العملية. نقدم خدمة تنظيف صمامات السحب بنفث الجوز دون فك المحرك."
   i3hAr="مشكلات المبخّر وضاغط التكييف"
   i3pAr="يعمل نظام التكييف في شيري عند أقصى طاقته 8 أشهر في السنة. المبخّر عرض لنمو العفن في الجو الساحلي الرطب. نجري خدمة تعقيم المبخر وفحص ضغط المبرد عند كل صيانة شاملة."
   i4hAr="تآكل التعليق والتوجيه على طرق الإمارات"
   i4pAr="طرق الإمارات تحتوي مطبات متكررة وبعض المقاطع الوعرة. بشات التحكم الأمامية وروابط الدرابزين تتآكل بشكل أسرع في الإمارات. الأعراض تشمل صوت طقطقة فوق المطبات وتذبذب في التوجيه."
   faq1qAr="كم تكلفة صيانة شيري في دبي؟"
   faq1aAr="تبدأ الصيانة الخفيفة من 280–400 درهم. الصيانة الشاملة كل 30,000 كم من 550–850 درهم."
   faq2qAr="كم مرة يجب تغيير سائل CVT في شيري Tiggo بدبي؟"
   faq2aAr="كل 40,000 كم في ظروف دبي. توصية المصنع 60,000 كم للمناخات المعتدلة. تكلفة استبدال CVT قد تتجاوز 8,000 درهم."
   faq3qAr="هل محرك شيري 1.6T موثوق في الإمارات؟"
   faq3aAr="عموماً نعم مع الصيانة الصحيحة. المتطلبات الأساسية: زيت تخليقي 5W-30 كل 7,500 كم وتنظيف الصمامات من الكربون كل 60,000 كم."
   faq4qAr="هل تخدم فيكس هايف شيري Omoda 5؟"
   faq4aAr="نعم. Omoda 5 موديل حديث لكننا نمتلك التغطية التشخيصية الكاملة. محرك 1.6T وناقل DCT مماثلان لأنظمة خط Tiggo."
   faq5qAr="ما أكثر مشكلات شيري شيوعاً في دبي؟"
   faq5aAr="تدهور سائل CVT وتراكم الكربون على محرك 1.6T وتآكل ضاغط التكييف وبشات التعليق الأمامي."
   ctaSubAr="رعاية محرك 1.6T وناقلات CVT وDCT ومعايرة ADAS — خدمة مستقلة متخصصة في دبي."
},

@{ slug="chevrolet"; name="Chevrolet"; nameAr="شيفروليه"
   title="Chevrolet Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Chevrolet repair in Dubai. Tahoe, Suburban, Silverado, Camaro, Malibu &amp; Traverse specialists. V8 engine, transmission &amp; suspension servicing. FixHive."
   models="Tahoe · Suburban · Silverado · Camaro · Traverse · Malibu · Trailblazer · Groove"
   heroSub="Dubai specialists for Chevrolet Tahoe, Suburban, Silverado and Camaro — 5.3L and 6.2L V8 engine care, 10-speed transmission and suspension servicing."
   intro1="Chevrolet is one of the most popular American brands in the UAE, with a strong presence across multiple segments — from the Tahoe and Suburban large SUVs that dominate airport transfer fleets and family use, to the Silverado pickup truck popular in commercial and contractor use, to the Camaro sports car. American V8 power has a devoted following in the UAE, and Chevrolet delivers it at price points that represent genuine value compared to European alternatives."
   intro2="The 5.3-litre and 6.2-litre EcoTec3 V8 engines, fitted to the Tahoe, Suburban and Silverado, are among the most proven American V8 designs. They use AFM (Active Fuel Management) cylinder deactivation and must be run on Dexos2 5W-30 full synthetic oil. In Dubai, oil changes every 8,000 km are essential; the OLM system's recommendations are based on American climate data and are not appropriate for UAE conditions. The 10-speed 10L80 automatic transmission fitted to current V8 models requires Dexos HP transmission fluid; substitution voids coverage and can cause shift quality issues."
   intro3="The Camaro SS and ZL1 represent Chevrolet's performance credentials — the SS uses the 6.2L LT1 and the ZL1 uses the supercharged 6.2L LT4 producing 650 horsepower. These cars require more frequent service than everyday vehicles in Dubai's climate. Track days at the Dubai Autodrome and Yas Circuit are popular with Camaro owners; we provide pre-track and post-track inspections to ensure safety-critical items are in order after high-speed, high-temperature use."
   i1h="AFM Lifter Failures on V8 Engines"
   i1p="Chevrolet's Active Fuel Management system on 5.3L and 6.2L V8 engines uses collapsible hydraulic lifters to deactivate four cylinders under light load. These lifters require constant, correct-pressure oil supply to function — if oil changes are delayed or incorrect oil is used, the small oil passages in the AFM lifters become restricted with sludge. This causes the lifter to stick in its collapsed position, generating a distinctive ticking noise and eventually a cylinder misfire. GM issued an updated lifter design and we can retrofit the improved parts while carrying out the repair. Prevention is always preferable: Dexos2 5W-30 oil, changed every 8,000 km."
   i2h="10-Speed Transmission Shift Flares &amp; Shudder"
   i2p="The 10L80 and 10L90 10-speed automatic transmissions on current Tahoe, Suburban and Silverado models are sophisticated but have shown sensitivity to fluid condition and clutch pack wear. In Dubai's stop-start traffic and frequent towing applications (desert camping equipment, boat trailers), the transmission operates in higher gear-change frequency and higher torque load conditions than in its design climate. Early symptoms include a slight shudder when engaging Drive from Park, a momentary 'flare' (engine rev without matching wheel acceleration) during upshifts, and an occasional harsh downshift. Transmission fluid flush with Dexos HP fluid at 60,000 km intervals prevents most of these issues."
   i3h="Front Differential &amp; Transfer Case Leaks"
   i3p="The Tahoe, Suburban and Silverado 4WD transfer case and front differential are common fluid leak locations on UAE-registered examples. Desert driving — even occasional weekend use — cycles the drivetrain components through heat ranges that accelerate seal degradation. The front differential pinion seal and the transfer case rear output seal are the most frequent leak points. Minor leaks left unattended can lead to complete differential dry-running and catastrophic gear damage. We inspect all drivetrain seals at every oil change and carry the full range of Chevrolet 4WD sealing components."
   i4h="Cooling System Failures Under UAE Heat"
   i4p="The 5.3L and 6.2L V8 cooling systems are adequately sized for normal operating conditions, but sustained high-speed highway driving in 46°C+ with a full passenger load and heavy AC use can push coolant temperature higher than the thermostat's comfortable operating range. The factory thermostat opens at 87°C; in UAE conditions the 82°C 'cool thermostat' upgrade is a popular and beneficial modification that keeps coolant temperature more consistently in the safe zone. We also inspect the electric cooling fans and coolant reservoir cap seal at every service — both are common failure items on high-mileage UAE Tahoes."
   faq1q="How much does Chevrolet servicing cost in Dubai?"
   faq1a="Minor Chevrolet V8 services at FixHive covering oil change, filter and multi-point inspection start from AED 400–550. Major services at 30,000 km intervals covering transmission fluid, differential fluid, spark plugs and full brake inspection range from AED 900–1,500 depending on model."
   faq2q="What oil does a Chevrolet V8 need in Dubai?"
   faq2a="All EcoTec3 V8 engines (5.3L and 6.2L) require Dexos2 certified full synthetic 5W-30. This is not negotiable — non-Dexos oil used in an AFM-equipped engine will eventually cause lifter failures. We change oil every 8,000 km for UAE-driven Chevrolets."
   faq3q="How often should I service a Chevrolet Tahoe or Suburban in Dubai?"
   faq3a="Oil changes every 8,000 km or annually. Transmission fluid every 60,000 km. Differential and transfer case fluid every 50,000 km or annually if off-road use is frequent. Spark plugs at 80,000 km (iridium tips are factory fit). Brake fluid annually."
   faq4q="What are the most common Chevrolet problems in the UAE?"
   faq4a="AFM lifter noise and eventual failure on V8 models, 10-speed transmission shift quality issues, front differential and transfer case leaks on 4WD models, and cooling system stress at highway speeds in summer are the most frequent items we see on UAE Chevrolets."
   faq5q="Does FixHive service the Chevrolet Camaro in Dubai?"
   faq5a="Yes, including both the Camaro SS and ZL1 supercharged variants. We provide pre/post track inspections, oil changes with the correct Dexos2 fluid, brake system inspections and complete mechanical servicing for all Camaro variants."
   ctaSub="V8 EcoTec3 engine care, 10-speed transmission and 4WD drivetrain — Chevrolet specialists in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Chevrolet%20service"
   relatedEn='<a href="gmc-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">GMC</a><a href="cadillac-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Cadillac</a><a href="ford-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Ford</a><a href="dodge-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Dodge</a><a href="nissan-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Nissan</a>'
   titleAr="إصلاح شيفروليه في دبي | Tahoe، Suburban، Silverado | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة شيفروليه في دبي. Tahoe وSuburban وSilverado وCamaro وTraverse. محرك V8 وناقل 10 سرعات."
   heroSubAr="متخصصون في شيفروليه Tahoe وSuburban وSilverado وCamaro — محرك V8 5.3 و6.2 لتر وناقل 10 سرعات وخدمة التعليق."
   intro1Ar="شيفروليه من أكثر العلامات الأمريكية شعبية في الإمارات بحضور قوي في قطاعات متعددة — من Tahoe وSuburban في SUVs الكبيرة إلى Silverado في الاستخدامات التجارية إلى Camaro الرياضية. قوة V8 الأمريكي لها متابعون متحمسون في الإمارات."
   intro2Ar="محركا EcoTec3 V8 بـ 5.3 و6.2 لتر من أكثر تصميمات V8 الأمريكية إثباتاً للجدارة. تستخدم نظام AFM وتتطلب زيت Dexos2 5W-30 تخليقي كامل. في دبي تغيير الزيت كل 8,000 كم ضروري."
   intro3Ar="Camaro SS وZL1 يمثلان قدرات شيفروليه الأدائية. هذه السيارات تحتاج صيانة أكثر تكراراً في مناخ دبي. نقدم فحص ما قبل وبعد مضمار السباق للتأكد من سلامة العناصر الحرجة."
   i1hAr="أعطال رافعات AFM في محركات V8"
   i1pAr="نظام AFM يستخدم رافعات هيدروليكية قابلة للطي. إذا تراكمت الترسبات في ممرات الرافعات الدقيقة يتعطل عملها. نتيجة: صوت طرق مميز وتعطل أسطوانة. نجري إصلاح الرافعات بالتصميم المحسّن من GM."
   i2hAr="تذبذبات ناقل 10 سرعات واهتزازات التحويل"
   i2pAr="ناقلات 10L80 و10L90 ذات 10 سرعات في Tahoe وSuburban وSilverado الحالية حساسة لحالة السائل. في ازدحام دبي والسحب تعمل عند تردد تحويل أعلى. تغيير سائل Dexos HP كل 60,000 كم يمنع معظم هذه المشكلات."
   i3hAr="تسرب التفاضل الأمامي وعلبة نقل الحركة"
   i3pAr="تسرب زيت التفاضل الأمامي وعلبة نقل الحركة شائع في نماذج الدفع الرباعي المسجلة بالإمارات. القيادة في الصحراء تُسرّع تدهور الأختام. التسربات الصغيرة إذا تُركت قد تؤدي لتدمير التروس."
   i4hAr="أعطال نظام التبريد في حرارة الإمارات"
   i4pAr="القيادة بسرعة عالية عند 46°C+ مع حمل كامل وتكييف مكثف قد ترفع درجة حرارة سائل التبريد. ترقية الثرموستات من 87°C إلى 82°C إجراء مفيد ومشهور لدى أصحاب Tahoe في الإمارات."
   faq1qAr="كم تكلفة صيانة شيفروليه V8 في دبي؟"
   faq1aAr="تبدأ الصيانة الخفيفة من 400–550 درهم. الصيانة الكبرى كل 30,000 كم من 900–1,500 درهم."
   faq2qAr="ما الزيت الموصى به لشيفروليه V8 في دبي؟"
   faq2aAr="جميع محركات EcoTec3 V8 تتطلب Dexos2 تخليقي كامل 5W-30. هذا ليس قابلاً للتفاوض — الزيت غير المعتمد من Dexos في محرك AFM سيتسبب في أعطال الرافعات."
   faq3qAr="كم مرة يجب صيانة شيفروليه Tahoe أو Suburban في دبي؟"
   faq3aAr="تغيير الزيت كل 8,000 كم. سائل ناقل الحركة كل 60,000 كم. سائل التفاضل وعلبة النقل كل 50,000 كم. شمعات الإشعال عند 80,000 كم. سائل الفرامل سنوياً."
   faq4qAr="ما أكثر مشكلات شيفروليه في الإمارات شيوعاً؟"
   faq4aAr="صوت رافعات AFM وأعطالها في V8، ومشكلات جودة التحويل في ناقل 10 سرعات، وتسربات التفاضل الأمامي وعلبة النقل، وضغط نظام التبريد في الطرق السريعة صيفاً."
   faq5qAr="هل تخدم فيكس هايف شيفروليه Camaro في دبي؟"
   faq5aAr="نعم بما يشمل SS وZL1 المضغوطة. نقدم فحص ما قبل وبعد المضمار وتغيير الزيت بسائل Dexos2 الصحيح وفحص نظام الفرامل."
   ctaSubAr="رعاية محرك V8 EcoTec3 وناقل 10 سرعات ودفع رباعي 4WD — متخصصو شيفروليه في دبي."
},

@{ slug="chrysler"; name="Chrysler"; nameAr="كرايسلر"
   title="Chrysler Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Chrysler repair in Dubai. 300C, Pacifica &amp; 300S specialists. HEMI V8, Pentastar V6 &amp; 8-speed transmission servicing. FixHive Garage Dubai."
   models="300C · 300S · Pacifica · 300C Platinum"
   heroSub="Dubai specialists for Chrysler 300C and Pacifica — HEMI V8, Pentastar V6, ZF 8-speed transmission and air suspension servicing."
   intro1="The Chrysler 300C is a genuinely distinctive presence on Dubai's roads — a full-size American luxury saloon with rear-wheel drive and available HEMI V8 power that makes an emphatic statement without the European price tag. Its bold styling, long wheelbase and spacious interior have made it a perennial favourite for private hire operators and business use across the UAE. The Pacifica, sold here as a premium minivan, is popular with larger families seeking American space and comfort."
   intro2="The 300C's HEMI 5.7-litre V8 uses Multi-Displacement System (MDS) cylinder deactivation, similar in principle to GM's AFM. Like the GM system, it requires strict adherence to Chrysler's Pennzoil Ultra Platinum or equivalent 0W-40 full synthetic oil specification; incorrect oil viscosity causes the MDS solenoids to function incorrectly in heat. The 3.6-litre Pentastar V6 — an outstanding engine — is simpler and more forgiving but equally benefits from quality synthetic oil at correct intervals. Both engines pair with the ZF-sourced 8HP 8-speed automatic transmission, one of the finest automatic gearboxes ever built."
   intro3="The ZF 8HP is a robust transmission but it benefits from fluid changes that the manufacturer marks as 'lifetime fill' — a claim made for temperate climate operation. In Dubai's heat we recommend a drain-and-fill every 60,000 km to maintain shift quality and torque converter health. The 300C's air suspension option (available on Limited and Platinum) uses a single compressor and four air springs; we service all components and hold 300C air suspension parts in stock."
   i1h="MDS Solenoid &amp; Lifter Failures on HEMI V8"
   i1p="The HEMI V8's MDS system uses solenoids to route oil to collapsible lifters for cylinder deactivation. In UAE conditions, if oil changes are delayed or if the car is frequently started and shut down in short trips — a common pattern with Dubai parking habits — sludge can accumulate in the solenoid passages, causing the MDS to leave cylinders deactivated when they should be active. This produces a rough, loping idle and occasional misfires. We service the MDS solenoids and, if required, replace the lifters with the updated MDS-delete kit that removes the system entirely for owners who prefer simplicity."
   i2h="Cooling System Stress at Highway Speeds"
   i2p="The Chrysler 300C's HEMI V8 generates significant heat under sustained high-speed driving, and Dubai's ambient temperatures can push the cooling system to its limits during summer motorway runs. The electric cooling fan module — which controls both the primary and secondary cooling fans — is a known failure item on higher-mileage 300C models, particularly when exposed to the thermal cycling of UAE summers. A partially functioning fan module allows coolant to run hot without triggering an immediate warning. We test fan module output current at every service and carry 300C fan modules in stock."
   i3h="Air Suspension Compressor &amp; Height Sensor Wear"
   i3p="The optional air suspension on 300C Platinum models requires the same preventive attention as any Chrysler Group air suspension system. The compressor is the primary failure item — cycling more frequently in UAE heat. Height sensors on lower wishbone mounts are exposed to road debris and can give incorrect height readings, causing the system to run the compressor unnecessarily. We inspect all four height sensors and the compressor output pressure at every service on air-suspended 300C variants."
   i4h="Transmission Shudder &amp; Torque Converter Issues"
   i4p="The ZF 8HP transmission in the 300C is inherently excellent, but like all ZF units it benefits from fresh fluid. In Dubai, where the 300C is often used as a hire car or business vehicle covering high mileage in stop-start conditions, transmission fluid degrades faster than the 'lifetime fill' narrative suggests. Symptoms of overdue fluid include a subtle shudder at light throttle in third and fourth gear — typically the torque converter lockup clutch juddering. A drain-and-fill with ZF Lifeguard 8 fluid resolves most shudder complaints within a few hundred kilometres."
   faq1q="How much does Chrysler 300C servicing cost in Dubai?"
   faq1a="Minor 300C services at FixHive covering oil change, filter and inspection start from AED 380–500 for V6 and AED 450–600 for HEMI V8. Major services every 30,000 km range from AED 800–1,200 depending on specification."
   faq2q="How often should I change the transmission fluid on a Chrysler 300C?"
   faq2a="We recommend a drain-and-fill with ZF Lifeguard 8 every 60,000 km regardless of the 'lifetime fill' marking. In Dubai's heat and with the 300C's usage patterns (often high-mileage business use), this interval is essential for preventing torque converter shudder and maintaining shift quality."
   faq3q="What oil does the HEMI V8 need in Dubai?"
   faq3a="The 5.7L HEMI requires 0W-40 full synthetic oil meeting Chrysler MS-12633 specification — Pennzoil Ultra Platinum 0W-40 or equivalent. This is mandatory for MDS correct operation. Changed every 8,000 km in UAE conditions."
   faq4q="Does FixHive have diagnostic tools for Chrysler?"
   faq4a="Yes. We use FCA (Stellantis) diagnostic software covering the full Chrysler range including 300C, Pacifica and older LX models. This gives access to all fault codes, live data, adaptation and module programming functions."
   faq5q="What are common Chrysler 300C problems in Dubai?"
   faq5a="MDS solenoid issues and HEMI lifter wear, cooling fan module failures, air suspension compressor failures on Limited and Platinum models, and transmission torque converter shudder on high-mileage examples are the items we see most frequently."
   ctaSub="HEMI V8 and Pentastar V6 care, ZF 8-speed transmission and air suspension — Chrysler 300C specialists in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Chrysler%20service"
   relatedEn='<a href="dodge-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Dodge</a><a href="jeep-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Jeep</a><a href="chevrolet-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Chevrolet</a><a href="ford-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Ford</a><a href="ram-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">RAM</a>'
   titleAr="إصلاح كرايسلر في دبي | 300C، Pacifica | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة كرايسلر في دبي. 300C وPacifica. محرك HEMI V8 وPentastar V6 وناقل ZF 8 سرعات."
   heroSubAr="متخصصون في كرايسلر 300C وPacifica — محرك HEMI V8 وPentastar V6 وناقل ZF 8 سرعات وتعليق هوائي."
   intro1Ar="كرايسلر 300C حضور مميز في شوارع دبي — سيدان فاخرة أمريكية كبيرة بدفع خلفي ومحرك HEMI V8 تُقدّم ثقلاً وقوة دون السعر الأوروبي. أسلوبها الجريء وقاعدة عجلاتها الطويلة وداخليتها الفسيحة جعلتها مفضلة مستمرة لمشغّلي سيارات الأجرة الخاصة والاستخدام التجاري."
   intro2Ar="محرك HEMI 5.7 لتر V8 في 300C يستخدم نظام MDS لتعطيل أسطوانات مشابهاً لنظام AFM في GM. يتطلب مواصفة Chrysler MS-12633 بزيت 0W-40 تخليقي كامل. محرك Pentastar V6 3.6 لتر الرائع أبسط وأكثر تسامحاً. كلاهما يقترن بناقل ZF 8HP ذي 8 سرعات الاستثنائي."
   intro3Ar="ناقل ZF 8HP متين بطبيعته لكنه يستفيد من تغيير السائل الموسوم بـ 'ملء مدى الحياة' — ادعاء مصمَّم لظروف المناخ المعتدل. في حرارة دبي نوصي بتصريف وملء كل 60,000 كم."
   i1hAr="أعطال صمامات MDS والرافعات في HEMI V8"
   i1pAr="نظام MDS يستخدم صمامات لتوجيه الزيت إلى الرافعات القابلة للطي. في ظروف الإمارات قد تتراكم الترسبات في ممرات الصمامات مسببة أداء خشن وأحياناً خلل إشعال. نصلح الصمامات وإذا لزم نستبدل الرافعات بطقم حذف MDS."
   i2hAr="ضغط نظام التبريد على السرعات السريعة"
   i2pAr="محرك HEMI V8 يولّد حرارة كبيرة. وحدة مروحة التبريد الكهربائية عرضة للأعطال في المركبات عالية الكيلومترات بالإمارات. مروحة تعمل جزئياً تتيح للسائل الارتفاع دون تحذير فوري."
   i3hAr="تآكل ضاغط التعليق الهوائي وحساسات الارتفاع"
   i3pAr="التعليق الهوائي الاختياري في 300C Platinum يتطلب نفس الاهتمام الوقائي لأي نظام Chrysler Group الهوائي. حساسات الارتفاع معرضة للأتربة وتُعطي قراءات خاطئة."
   i4hAr="اهتزاز ناقل الحركة ومشكلات محول العزم"
   i4pAr="ناقل ZF 8HP الاستثنائي يستفيد من السائل الطازج. الأعراض: اهتزاز خفيف عند تعشيق قابض الإقفال في الثالثة والرابعة. تصريف وملء بسائل ZF Lifeguard 8 يحل معظم شكاوى الاهتزاز."
   faq1qAr="كم تكلفة صيانة كرايسلر 300C في دبي؟"
   faq1aAr="تبدأ الصيانة الخفيفة من 380–500 درهم لـ V6 و450–600 درهم لـ HEMI V8. الصيانة الشاملة من 800–1,200 درهم."
   faq2qAr="كم مرة يجب تغيير سائل ناقل الحركة في كرايسلر 300C؟"
   faq2aAr="نوصي بتصريف وملء بسائل ZF Lifeguard 8 كل 60,000 كم بغض النظر عن وسم 'ملء مدى الحياة'. في حرارة دبي وأنماط الاستخدام المكثف هذه الفترة ضرورية."
   faq3qAr="ما الزيت الموصى به لـ HEMI V8 في دبي؟"
   faq3aAr="يتطلب 5.7L HEMI زيت 0W-40 تخليقي كامل وفق مواصفة Chrysler MS-12633. يُغيَّر كل 8,000 كم في ظروف الإمارات."
   faq4qAr="هل تمتلك فيكس هايف أدوات تشخيص لكرايسلر؟"
   faq4aAr="نعم. نستخدم برنامج تشخيص FCA/Stellantis يغطي النطاق الكامل لكرايسلر بما يشمل 300C وPacifica."
   faq5qAr="ما أكثر مشكلات كرايسلر 300C شيوعاً في دبي؟"
   faq5aAr="مشكلات صمامات MDS وتآكل رافعات HEMI، وأعطال وحدة مروحة التبريد، وأعطال ضاغط التعليق الهوائي، واهتزاز ناقل الحركة في النماذج عالية الكيلومترات."
   ctaSubAr="رعاية HEMI V8 وPentastar V6 وناقل ZF 8 سرعات وتعليق هوائي — متخصصو كرايسلر 300C في دبي."
},

@{ slug="dodge"; name="Dodge"; nameAr="دودج"
   title="Dodge Repair &amp; Service Dubai | FixHive Garage"
   desc="Expert Dodge repair in Dubai. Charger, Challenger, Durango &amp; Dodge 1500 specialists. HEMI V8, SRT Hellcat &amp; Demon engine servicing. FixHive Garage Dubai."
   models="Charger · Challenger · Durango · RAM 1500 Classic · Durango SRT"
   heroSub="Dubai specialists for Dodge Charger, Challenger and Durango — 5.7L and 6.4L HEMI V8, SRT Hellcat supercharged and Widebody servicing."
   intro1="Dodge occupies a unique position in Dubai's automotive market — the brand of unapologetically American muscle, where the Charger and Challenger have loyal followings among enthusiasts who appreciate the combination of powerful V8 engines, rear-wheel drive and dramatic styling. The SRT models — Charger Hellcat, Challenger Hellcat and the 807-horsepower Challenger SRT Demon (a car that was never officially sold in the UAE but arrived via personal import) — are genuine performance icons with an active community of owners in Dubai and Abu Dhabi."
   intro2="The HEMI family covers the 5.7L (RT models), 6.4L 392 (Scat Pack and Durango SRT), and the 6.2L supercharged (Hellcat and Redeye). All use Multi-Displacement System (MDS) on the 5.7 and 6.4, requiring 0W-40 Chrysler MS-12633 oil. The Hellcat's supercharged 6.2L does not use MDS and is a more straightforward engine from a service perspective, but its supercharger drive belt and intercooler coolant are service items that standard 5.7 owners never encounter. The eight-speed ZF 8HP transmission serves all V8 Dodge models and is excellent but benefits from periodic fluid maintenance."
   intro3="Dubai's heat creates specific challenges for Dodge HEMI owners. The cars are often used enthusiastically — acceleration runs on empty evening roads, desert highway cruising — and these driving patterns combined with 45°C+ ambient temperatures place the cooling system, brake system and drivetrain under greater thermal stress than their American-market service intervals account for. FixHive provides complete Dodge HEMI service including supercharger service on Hellcat models, pre-track inspections and comprehensive diagnostic coverage."
   i1h="HEMI MDS Lifter Failure &amp; Engine Tick"
   i1p="The 5.7L and 6.4L HEMI's Multi-Displacement System uses collapsible lifters to deactivate four cylinders under light load. In UAE conditions — particularly with the short-trip pattern common in Dubai (AC pre-cooling, short drives to mall or restaurant, park for hours in heat) — the engine rarely reaches full operating temperature before shutdown, which prevents the oil from fully circulating through the MDS passages. This pattern, combined with any delay in oil changes, causes sludge in the MDS solenoid circuits and eventual lifter collapse. The characteristic 'HEMI tick' — a tapping noise from the engine — is the first symptom. We service the solenoids and replace lifters with the updated design or fit an MDS-delete kit for customers who prefer to disable the system."
   i2h="Hellcat Supercharger Drive Belt &amp; Intercooler"
   i2p="The 6.2L supercharged Hellcat engine uses a Roots-type positive displacement supercharger driven by a 6-rib accessory belt at approximately 2.3x crankshaft speed. In Dubai's heat, the supercharger inlet air temperature rises rapidly without the intercooler's chilled water system functioning correctly. The intercooler pump and its dedicated coolant reservoir are maintenance items that many independent workshops are unfamiliar with. The supercharger belt should be inspected every 30,000 km and replaced by 60,000 km — a belt failure on a running engine causes immediate catastrophic supercharger damage. We stock Hellcat supercharger belts and intercooler coolant."
   i3h="Brake Fade &amp; Rotor Warping Under UAE Conditions"
   i3p="Dodge's performance models — particularly the Challenger SRT and Durango SRT — are used enthusiastically by UAE owners who take advantage of Dubai's late-night traffic lull. Repeated hard braking from high speed causes brake rotor temperatures to reach glazing point on the standard cast-iron rotors. Rotor warping (producing a pulsating brake pedal) and pad glazing (reduced braking response despite pedal effort) are the consequences. We recommend upgrading to two-piece floating rotors on high-use Hellcat models and carry EBC Yellowstuff pads as a significant upgrade over stock for owners who regularly use their cars spiritedly."
   i4h="Rear Axle Seal Leaks &amp; Differential Service"
   i4p="The solid rear axle (8.25-inch and Dana 60 units) fitted to Dodge Charger and Challenger RWD models requires axle seal inspection at every major service. The axle seal gaskets are relatively simple components but in UAE conditions — where the car may sit in direct sunlight for hours at a time and the axle oil expands and contracts with heat cycles — seal degradation is accelerated. A leaking axle seal allows differential oil to coat the rear brakes and contaminate the brake pads, causing brake fade and eventually dangerous brake failure. We inspect and replace rear axle seals as preventive maintenance on all V8 Dodge models."
   faq1q="How much does Dodge HEMI servicing cost in Dubai?"
   faq1a="Minor Dodge V8 services at FixHive start from AED 450–600 covering oil change with 0W-40 MS-12633, filter, multi-point inspection and brake check. Major services every 30,000 km covering transmission fluid, differential service, spark plugs and supercharger belt inspection (Hellcat) range from AED 900–1,800."
   faq2q="What oil does a Dodge HEMI need in Dubai?"
   faq2a="5.7L and 6.4L HEMI engines require Chrysler MS-12633 0W-40 full synthetic. The 6.2L Hellcat uses the same specification. Never use 5W-20 or 5W-30 in a UAE-driven HEMI — the MDS system relies on the 0W-40 viscosity curve for correct solenoid oil pressure."
   faq3q="How often should I service a Dodge Challenger or Charger in Dubai?"
   faq3a="Oil changes every 8,000 km or annually. Transmission fluid (ZF Lifeguard 8) every 60,000 km. Differential oil every 40,000 km. Brake fluid annually. Supercharger belt inspection every 30,000 km (Hellcat). Air filter every 15,000 km."
   faq4q="Can FixHive service the Dodge Challenger Hellcat and SRT in Dubai?"
   faq4a="Yes. The Hellcat's 6.2L supercharged engine, intercooler system and wide-body brake package are all within our capability. We have serviced multiple Hellcats, Redeyes and a small number of Demons in the UAE."
   faq5q="What are common Dodge problems in Dubai?"
   faq5a="HEMI tick (MDS lifter wear), transmission torque converter shudder on overdue-service examples, rear axle seal leaks and brake rotor warping from enthusiastic use are the most common items on UAE Dodge vehicles."
   ctaSub="HEMI V8, Hellcat supercharger, ZF 8-speed and rear axle service — Dodge muscle car specialists in Dubai."
   waMsg="Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Dodge%20service"
   relatedEn='<a href="chrysler-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Chrysler</a><a href="jeep-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Jeep</a><a href="chevrolet-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Chevrolet</a><a href="ford-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">Ford</a><a href="ram-repair-dubai.html" style="padding:0.5rem 1.1rem;background:#f0f4ff;border:1.5px solid #c7d2fe;border-radius:20px;text-decoration:none;color:#1e3a8a;font-size:0.88rem;font-weight:600;">RAM</a>'
   titleAr="إصلاح دودج في دبي | Charger، Challenger، Durango | فيكس هايف"
   descAr="متخصصون في إصلاح وصيانة دودج في دبي. Charger وChallenger وDurango. محرك HEMI V8 وHellcat المضغوط وناقل ZF 8 سرعات."
   heroSubAr="متخصصون في دودج Charger وChallenger وDurango — محرك HEMI V8 بـ 5.7 و6.4 لتر وHellcat المضغوط وWidebody."
   intro1Ar="دودج تحتل مكانة فريدة في سوق دبي — العلامة الأمريكية العضلية بلا اعتذار، حيث يتمتع Charger وChallenger بمتابعين مخلصين من عشاق محركات V8 القوية ودفع الخلف والتصميم الدرامي. موديلات SRT — Charger Hellcat وChallenger Hellcat والـ 807 حصان Demon — أيقونات أداء حقيقية لها مجتمع نشط من الملاك في دبي وأبوظبي."
   intro2Ar="عائلة HEMI تضم 5.7L (موديلات RT) و6.4L 392 (Scat Pack وDurango SRT) و6.2L مضغوط (Hellcat وRedeye). جميعها تستخدم MDS في 5.7 و6.4 وتتطلب زيت 0W-40 Chrysler MS-12633. ناقل ZF 8HP يخدم جميع موديلات V8."
   intro3Ar="حرارة دبي تخلق تحديات للملاك. السيارات كثيراً ما تُستخدم بحماس — تسارع على الطرق الخالية مساءً وتجوال في الصحراء — مما يضع نظام التبريد والفرامل ومنظومة الدفع تحت ضغط حراري أكبر مما تحسبه فترات الصيانة الأمريكية."
   i1hAr="تعطل رافعات MDS وصوت طرق HEMI"
   i1pAr="نظام MDS في HEMI 5.7 و6.4 يستخدم رافعات قابلة للطي. في ظروف الإمارات مع أنماط الرحلات القصيرة نادراً ما يصل المحرك لدرجة الحرارة الكاملة قبل الإيقاف مما يمنع الزيت من الدوران الكامل في ممرات MDS. الأعراض: 'طرقة HEMI' المميزة."
   i2hAr="حزام ضاغط Hellcat والمبادل الحراري"
   i2pAr="محرك Hellcat 6.2L يستخدم ضاغطاً جذرياً مدفوعاً بسرعة 2.3 ضعف سرعة عمود المرفق. مضخة المبادل الحراري وخزانه المخصص عناصر صيانة يجهلها كثير من الورش. حزام الضاغط يجب فحصه كل 30,000 كم."
   i3hAr="تلاشي الفرامل وتشوه الأقراص في ظروف الإمارات"
   i3pAr="موديلات الأداء تُستخدم بحماس. الفرملة الشديدة المتكررة من سرعة عالية ترفع حرارة الأقراص الحديدية إلى نقطة التزجج. نوصي بالترقية لأقراص ذات جزأين عائمة لموديلات Hellcat كثيرة الاستخدام."
   i4hAr="تسرب أختام محور الخلف وخدمة التفاضل"
   i4pAr="محور الخلف الصلب في Charger وChallenger يحتاج فحص أختام عند كل صيانة كبرى. أختام المحور تتدهور بشكل أسرع في ظروف الإمارات بسبب دورات التمدد والانكماش الحراري."
   faq1qAr="كم تكلفة صيانة دودج HEMI في دبي؟"
   faq1aAr="تبدأ الصيانة الخفيفة من 450–600 درهم. الصيانة الشاملة من 900–1,800 درهم."
   faq2qAr="ما الزيت الموصى به لدودج HEMI في دبي؟"
   faq2aAr="محركات HEMI 5.7 و6.4 و6.2 تتطلب Chrysler MS-12633 0W-40 تخليقي كامل. لا تستخدم 5W-20 أو 5W-30 في HEMI مُشغَّل بالإمارات."
   faq3qAr="كم مرة يجب صيانة دودج Challenger أو Charger في دبي؟"
   faq3aAr="تغيير الزيت كل 8,000 كم. سائل ناقل الحركة كل 60,000 كم. زيت التفاضل كل 40,000 كم. سائل الفرامل سنوياً."
   faq4qAr="هل تستطيع فيكس هايف خدمة دودج Challenger Hellcat في دبي؟"
   faq4aAr="نعم. محرك Hellcat 6.2L المضغوط ونظام المبادل الحراري وحزمة الفرامل العريضة كلها ضمن قدراتنا. خدّمنا عدة سيارات Hellcat وRedeye ودودج Demon في الإمارات."
   faq5qAr="ما أكثر مشكلات دودج شيوعاً في دبي؟"
   faq5aAr="طرقة HEMI وتعطل رافعات MDS، واهتزاز ناقل الحركة في نماذج متأخرة الصيانة، وتسرب أختام المحور الخلفي، وتشوه الأقراص من الاستخدام الحماسي."
   ctaSubAr="صيانة HEMI V8 وضاغط Hellcat وZF 8 سرعات والمحور الخلفي — متخصصو دودج في دبي."
}
)

foreach ($b in $brands2) {
  $enPath = Join-Path $base "$($b.slug)-repair-dubai.html"
  $arPath = Join-Path $base "ar\$($b.slug)-repair-dubai.html"
  $en = New-ENPage $b
  $ar = New-ARPage $b
  [System.IO.File]::WriteAllText($enPath, $en, [System.Text.Encoding]::UTF8)
  [System.IO.File]::WriteAllText($arPath, $ar, [System.Text.Encoding]::UTF8)
  Write-Host "Created: $($b.slug)"
}
Write-Host "Part 2 done (5 more brands). Run gen-brands-3.ps1 for remaining brands."
