# gen-brands-3.ps1 — Ferrari through Rolls-Royce (15 brands)
. "$PSScriptRoot\gen-brands.ps1"

$brands3 = @(
  @{
    slug="ferrari"; name="Ferrari"; nameAr="فيراري"
    title="Ferrari Repair Dubai | Expert Ferrari Service UAE"
    desc="Specialist Ferrari repair in Dubai. Certified technicians, genuine parts, and precision diagnostics for all Ferrari models including Roma, SF90, 296 GTB and more."
    models="Roma, SF90 Stradale, 296 GTB, F8 Tributo, Portofino M, 812 Superfast, Purosangue"
    heroSub="Precision Italian Supercar Engineering in Dubai"
    intro1="FixHive delivers factory-level Ferrari service in Dubai with specialist technicians trained on Maranello engineering standards."
    intro2="From routine oil changes to complex transmission rebuilds, every Ferrari repair uses OEM-approved parts and manufacturer-specified procedures."
    intro3="Our state-of-the-art diagnostic equipment reads Ferrari's proprietary ECU systems, ensuring accurate fault identification and lasting repairs."
    i1h="Ferrari Diagnostics" ; i1p="Advanced dealer-grade diagnostic tools read every Ferrari ECU, ABS, and suspension module for pinpoint accuracy."
    i2h="Engine & Gearbox" ; i2p="Specialist care for Ferrari's high-revving V8 and V12 engines plus dual-clutch gearbox service and calibration."
    i3h="Genuine Parts" ; i3p="Only OEM or approved aftermarket components are used, preserving your Ferrari's performance and warranty compliance."
    i4h="Performance Tuning" ; i4p="ECU recalibration, exhaust optimisation, and suspension setup tailored to Dubai's roads and track days."
    faq1q="Do you service all Ferrari models?" ; faq1a="Yes — from classic 360 Modena to the latest SF90 Stradale, we cover the full Ferrari range."
    faq2q="How long does a Ferrari service take?" ; faq2a="A standard annual service typically takes one to two days; complex repairs are quoted case by case."
    faq3q="Do you use genuine Ferrari parts?" ; faq3a="Yes, we source OEM Ferrari parts and approved alternatives to maintain manufacturer standards."
    faq4q="Can you repair Ferrari carbon-ceramic brakes?" ; faq4a="Yes, our technicians are equipped to inspect, machine, and replace Ferrari CCM brake systems."
    faq5q="Do you offer collection and delivery?" ; faq5a="Yes, we offer complimentary collection and delivery across Dubai for Ferrari customers."
    ctaSub="Book your Ferrari service with Dubai's supercar specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Ferrari"
    relatedEn="lamborghini-repair-dubai.html|Lamborghini,maserati-repair-dubai.html|Maserati,porsche-repair-dubai.html|Porsche"
    titleAr="إصلاح فيراري دبي | خدمة فيراري المتخصصة في الإمارات"
    descAr="خدمة فيراري متخصصة في دبي. فنيون معتمدون وقطع غيار أصلية وتشخيص دقيق لجميع موديلات فيراري."
    heroSubAr="هندسة السيارات الإيطالية الفائقة في دبي"
    intro1Ar="تقدم فيكس هايف خدمة فيراري بمستوى المصنع في دبي مع فنيين متخصصين مدربين على معايير مارانيلو."
    intro2Ar="من تغيير الزيت الروتيني إلى إصلاح ناقل الحركة، نستخدم قطع غيار معتمدة من المصنع."
    intro3Ar="أجهزة التشخيص المتطورة لدينا تقرأ أنظمة ECU الخاصة بفيراري لتحديد الأعطال بدقة."
    i1hAr="تشخيص فيراري" ; i1pAr="أدوات تشخيص على مستوى الوكيل لقراءة كل وحدة تحكم في فيراري."
    i2hAr="المحرك وناقل الحركة" ; i2pAr="رعاية متخصصة لمحركات V8 وV12 وخدمة علبة التروس."
    i3hAr="قطع غيار أصلية" ; i3pAr="نستخدم فقط مكونات OEM أو المعتمدة للحفاظ على أداء فيراري."
    i4hAr="ضبط الأداء" ; i4pAr="إعادة معايرة ECU وتحسين العادم وإعداد التعليق."
    faq1qAr="هل تخدمون جميع موديلات فيراري؟" ; faq1aAr="نعم، نغطي كامل نطاق فيراري من الكلاسيكية إلى الأحدث."
    faq2qAr="كم يستغرق صيانة فيراري؟" ; faq2aAr="الصيانة السنوية تستغرق عادةً يومًا إلى يومين."
    faq3qAr="هل تستخدمون قطع غيار أصلية؟" ; faq3aAr="نعم، نستخدم قطع OEM أو بدائل معتمدة."
    faq4qAr="هل تصلحون فرامل CCM لفيراري؟" ; faq4aAr="نعم، فنيونا مجهزون للفحص والاستبدال."
    faq5qAr="هل تقدمون خدمة الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم استلامًا وتسليمًا مجانيًا في دبي."
    ctaSubAr="احجز صيانة فيراري مع متخصصي السيارات الفائقة في دبي."
  },
  @{
    slug="gac"; name="GAC"; nameAr="جي إيه سي"
    title="GAC Repair Dubai | GAC Service Centre UAE"
    desc="Expert GAC repair and servicing in Dubai. Qualified technicians, genuine parts, and full diagnostics for all GAC models including Trumpchi, GS and GA series."
    models="GS3, GS4, GS8, GA4, GA6, Trumpchi M6, Aion S"
    heroSub="Professional GAC Service in the Heart of Dubai"
    intro1="FixHive provides comprehensive GAC repair and maintenance services in Dubai, keeping your vehicle performing to Chinese-engineering standards."
    intro2="Our technicians are trained on GAC's electronic and mechanical systems, delivering accurate diagnostics and efficient repairs."
    intro3="We stock common GAC parts and can source specialist components quickly, minimising your vehicle's downtime."
    i1h="GAC Diagnostics" ; i1p="Up-to-date scan tools read GAC's onboard systems covering engine, transmission, ADAS, and more."
    i2h="Engine Service" ; i2p="Full engine maintenance including timing, oil systems, and cooling — keeping your GAC running efficiently."
    i3h="Genuine Parts" ; i3p="OEM and approved parts sourced directly, ensuring lasting quality and manufacturer compliance."
    i4h="Electrical & ADAS" ; i4p="Calibration and repair of GAC's safety and driver-assistance systems by trained specialists."
    faq1q="Which GAC models do you service?" ; faq1a="All GAC models including GS3, GS4, GS8, GA4, GA6, Trumpchi, and Aion EV models."
    faq2q="How often should my GAC be serviced?" ; faq2a="Every 10,000 km or 12 months, whichever comes first, as per GAC guidelines."
    faq3q="Do you use genuine GAC parts?" ; faq3a="Yes, we use OEM GAC parts and approved equivalents for all repairs."
    faq4q="Can you reset GAC service reminders?" ; faq4a="Yes, our diagnostic tools fully reset GAC service indicators and fault codes."
    faq5q="Do you offer pickup and drop-off?" ; faq5a="Yes, we offer convenient collection and delivery across Dubai."
    ctaSub="Book your GAC service with Dubai's trusted specialists today."
    waMsg="Hi FixHive, I need a service/repair for my GAC"
    relatedEn="changan-repair-dubai.html|Changan,chery-repair-dubai.html|Chery,geely-repair-dubai.html|Geely"
    titleAr="إصلاح جي إيه سي دبي | مركز خدمة جي إيه سي الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات جي إيه سي في دبي. فنيون مؤهلون وقطع غيار أصلية."
    heroSubAr="خدمة جي إيه سي الاحترافية في قلب دبي"
    intro1Ar="تقدم فيكس هايف خدمات شاملة لإصلاح وصيانة جي إيه سي في دبي."
    intro2Ar="فنيونا مدربون على أنظمة جي إيه سي الإلكترونية والميكانيكية."
    intro3Ar="نحتفظ بقطع الغيار الشائعة ويمكننا تأمين قطع خاصة بسرعة."
    i1hAr="تشخيص جي إيه سي" ; i1pAr="أدوات مسح حديثة تقرأ جميع أنظمة جي إيه سي."
    i2hAr="خدمة المحرك" ; i2pAr="صيانة كاملة للمحرك بما فيها التوقيت وأنظمة الزيت."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM ومعتمدة لضمان الجودة."
    i4hAr="الكهرباء وأنظمة ADAS" ; i4pAr="معايرة وإصلاح أنظمة السلامة ومساعدة السائق."
    faq1qAr="ما موديلات جي إيه سي التي تخدمونها؟" ; faq1aAr="جميع موديلات جي إيه سي بما فيها GS وGA وAion."
    faq2qAr="كم مرة يجب صيانة سيارتي؟" ; faq2aAr="كل 10,000 كم أو 12 شهرًا أيهما أسبق."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، نستخدم قطع OEM أو معادلات معتمدة."
    faq4qAr="هل يمكنكم إعادة ضبط مؤشر الخدمة؟" ; faq4aAr="نعم، أدواتنا تعيد ضبط مؤشرات الخدمة وأكواد الأعطال."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم الاستلام والتسليم في دبي."
    ctaSubAr="احجز صيانة جي إيه سي مع متخصصي دبي الموثوقين."
  },
  @{
    slug="geely"; name="Geely"; nameAr="جيلي"
    title="Geely Repair Dubai | Geely Service Centre UAE"
    desc="Professional Geely repair and servicing in Dubai. Expert technicians, genuine parts, and advanced diagnostics for Coolray, Tugella, Emgrand and all Geely models."
    models="Coolray, Tugella, Emgrand, Atlas Pro, Okavango, Preface, Monjaro"
    heroSub="Expert Geely Service You Can Rely On"
    intro1="FixHive is Dubai's trusted Geely service centre, delivering manufacturer-standard care for every model in the Geely range."
    intro2="Our technicians use Geely-specific diagnostic software to identify issues quickly and apply precise, lasting repairs."
    intro3="From oil changes to complex electrical repairs, every Geely job is completed with genuine parts and full attention to detail."
    i1h="Geely Diagnostics" ; i1p="Manufacturer-grade scan tools cover all Geely ECUs including ADAS, powertrain, and body control modules."
    i2h="Coolray & Tugella Service" ; i2p="Full service packages for Geely's popular SUV lineup, including DSG gearbox and turbocharged engine care."
    i3h="Genuine Parts" ; i3p="OEM Geely parts and approved alternatives keep your vehicle performing to factory specification."
    i4h="Hybrid & EV Support" ; i4p="Specialist support for Geely's electrified models including battery health checks and charging system diagnostics."
    faq1q="Which Geely models do you service?" ; faq1a="All Geely models — Coolray, Tugella, Emgrand, Atlas, Okavango, Preface, and Monjaro."
    faq2q="How often does my Geely need servicing?" ; faq2a="Every 10,000 km or 12 months as recommended by Geely."
    faq3q="Do you use genuine Geely parts?" ; faq3a="Yes, we use genuine OEM parts or manufacturer-approved alternatives."
    faq4q="Can you service Geely's DSG gearbox?" ; faq4a="Yes, our technicians are trained on Geely's dual-clutch gearbox systems."
    faq5q="Do you offer warranty on repairs?" ; faq5a="Yes, all our repairs carry a workmanship warranty for your peace of mind."
    ctaSub="Book your Geely service with Dubai's trusted specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Geely"
    relatedEn="changan-repair-dubai.html|Changan,chery-repair-dubai.html|Chery,gac-repair-dubai.html|GAC"
    titleAr="إصلاح جيلي دبي | مركز خدمة جيلي الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات جيلي في دبي. فنيون خبراء وقطع غيار أصلية."
    heroSubAr="خدمة جيلي الاحترافية الموثوقة"
    intro1Ar="فيكس هايف هي مركز خدمة جيلي الموثوق في دبي."
    intro2Ar="فنيونا يستخدمون برامج تشخيص خاصة بجيلي."
    intro3Ar="من تغيير الزيت إلى الإصلاحات الكهربائية المعقدة بقطع أصلية."
    i1hAr="تشخيص جيلي" ; i1pAr="أدوات مسح متخصصة تغطي جميع وحدات التحكم."
    i2hAr="خدمة Coolray وTugella" ; i2pAr="حزم خدمة كاملة لسيارات SUV الشهيرة من جيلي."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM ومعادلات معتمدة."
    i4hAr="دعم الهجين والكهربائي" ; i4pAr="دعم متخصص للموديلات الكهربائية من جيلي."
    faq1qAr="ما موديلات جيلي التي تخدمونها؟" ; faq1aAr="جميع موديلات جيلي بما فيها Coolray وTugella وEmgrand."
    faq2qAr="كم مرة تحتاج سيارتي للصيانة؟" ; faq2aAr="كل 10,000 كم أو 12 شهرًا."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، نستخدم قطع OEM أو معادلات معتمدة."
    faq4qAr="هل تخدمون علبة تروس DSG من جيلي؟" ; faq4aAr="نعم، فنيونا مدربون على أنظمة DSG."
    faq5qAr="هل تقدمون ضمانًا على الإصلاحات؟" ; faq5aAr="نعم، جميع إصلاحاتنا تحمل ضمان جودة."
    ctaSubAr="احجز صيانة جيلي مع متخصصي دبي الموثوقين."
  },
  @{
    slug="gmc"; name="GMC"; nameAr="جي إم سي"
    title="GMC Repair Dubai | GMC Service Centre UAE"
    desc="Expert GMC repair and servicing in Dubai. Specialist technicians, genuine parts, and comprehensive diagnostics for Yukon, Suburban, Sierra and all GMC models."
    models="Yukon, Yukon XL, Sierra, Terrain, Canyon, Acadia, Envoy"
    heroSub="Trusted GMC Service for Dubai's Road Warriors"
    intro1="FixHive delivers expert GMC repair and maintenance across Dubai, keeping America's most capable trucks and SUVs at peak performance."
    intro2="Our technicians have deep experience with GMC's robust V8 engines, four-wheel-drive systems, and advanced towing packages."
    intro3="From scheduled maintenance to complex drivetrain repairs, we use genuine GMC parts and factory-specified procedures throughout."
    i1h="GMC Diagnostics" ; i1p="GM Tech 2 and GDS2-compatible tools ensure full coverage of all GMC modules and subsystems."
    i2h="V8 Engine Service" ; i2p="Expert care for GMC's 5.3L and 6.2L EcoTec3 engines, including AFM/DFM system maintenance."
    i3h="4WD & Drivetrain" ; i3p="Four-wheel-drive transfer case service, differential rebuilds, and driveshaft repairs."
    i4h="Towing & Suspension" ; i4p="Levelling kits, leaf spring service, airbag suspension, and trailer hitch inspections."
    faq1q="Which GMC models do you service?" ; faq1a="All GMC models — Yukon, Sierra, Terrain, Canyon, Acadia, and more."
    faq2q="How often should my GMC be serviced?" ; faq2a="Every 8,000–12,000 km depending on model and driving conditions, or as the oil-life monitor indicates."
    faq3q="Can you work on GMC 4WD systems?" ; faq3a="Yes, we service all GMC four-wheel-drive and all-wheel-drive transfer cases and differentials."
    faq4q="Do you use genuine GM parts?" ; faq4a="Yes, we use ACDelco and genuine GM parts to maintain your warranty and performance."
    faq5q="Do you offer a pickup service?" ; faq5a="Yes, we offer convenient vehicle pickup and delivery across Dubai."
    ctaSub="Book your GMC service with Dubai's American truck specialists today."
    waMsg="Hi FixHive, I need a service/repair for my GMC"
    relatedEn="chevrolet-repair-dubai.html|Chevrolet,cadillac-repair-dubai.html|Cadillac,ford-repair-dubai.html|Ford"
    titleAr="إصلاح جي إم سي دبي | مركز خدمة جي إم سي الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات جي إم سي في دبي. فنيون متخصصون وقطع غيار أصلية."
    heroSubAr="خدمة جي إم سي الموثوقة لسائقي دبي"
    intro1Ar="تقدم فيكس هايف إصلاحًا وصيانةً متخصصةً لجي إم سي في دبي."
    intro2Ar="فنيونا لديهم خبرة واسعة في محركات V8 وأنظمة الدفع الرباعي."
    intro3Ar="من الصيانة الدورية إلى إصلاحات ناقل الحركة بقطع أصلية."
    i1hAr="تشخيص جي إم سي" ; i1pAr="أدوات متوافقة مع GM Tech 2 وGDS2."
    i2hAr="خدمة محرك V8" ; i2pAr="رعاية متخصصة لمحركات EcoTec3."
    i3hAr="نظام الدفع الرباعي" ; i3pAr="خدمة علبة نقل الحركة والتفاضلية."
    i4hAr="قدرة الجر والتعليق" ; i4pAr="مجموعات التسوية وخدمة الزنبركات الورقية."
    faq1qAr="ما موديلات جي إم سي التي تخدمونها؟" ; faq1aAr="جميع موديلات جي إم سي بما فيها Yukon وSierra."
    faq2qAr="كم مرة يجب صيانة سيارتي؟" ; faq2aAr="كل 8,000-12,000 كم أو حسب مؤشر عمر الزيت."
    faq3qAr="هل تعملون على أنظمة الدفع الرباعي؟" ; faq3aAr="نعم، نخدم جميع أنظمة 4WD وAWD."
    faq4qAr="هل تستخدمون قطع GM أصلية؟" ; faq4aAr="نعم، نستخدم قطع ACDelco وGM الأصلية."
    faq5qAr="هل تقدمون خدمة الاستلام؟" ; faq5aAr="نعم، نقدم الاستلام والتسليم في دبي."
    ctaSubAr="احجز صيانة جي إم سي مع متخصصي الشاحنات الأمريكية في دبي."
  },
  @{
    slug="haval"; name="Haval"; nameAr="هافال"
    title="Haval Repair Dubai | Haval Service Centre UAE"
    desc="Professional Haval repair and servicing in Dubai. Qualified technicians, genuine parts, and full diagnostics for H6, H9, Jolion, Dargo and all Haval models."
    models="H6, H9, Jolion, Dargo, H2, H5, Big Dog"
    heroSub="Reliable Haval Service from Dubai Experts"
    intro1="FixHive provides thorough Haval repair and maintenance in Dubai, delivering the reliability and longevity your Haval deserves."
    intro2="Our team is trained on Haval's turbocharged engines, dual-clutch gearboxes, and advanced four-wheel-drive systems."
    intro3="We hold common Haval parts in stock and can source specialist items rapidly, ensuring minimal vehicle downtime."
    i1h="Haval Diagnostics" ; i1p="Current-model scan tools cover all Haval ECUs for accurate fault reading and system resets."
    i2h="Turbo & DCT Service" ; i2p="Expert maintenance of Haval's 1.5T and 2.0T engines and dual-clutch transmission systems."
    i3h="Genuine Parts" ; i3p="OEM Haval parts or approved equivalents for every repair, preserving factory performance."
    i4h="4WD System Care" ; i4p="Transfer case service, Torsen differential maintenance, and terrain mode calibration."
    faq1q="Which Haval models do you service?" ; faq1a="All Haval models including H6, H9, Jolion, Dargo, and the full SUV lineup."
    faq2q="How often should my Haval be serviced?" ; faq2a="Every 10,000 km or 12 months, whichever comes first."
    faq3q="Can you service Haval's dual-clutch gearbox?" ; faq3a="Yes, we have trained technicians for Haval's 7-speed and 8-speed DCT systems."
    faq4q="Do you stock Haval spare parts?" ; faq4a="Yes, we keep common wear items in stock and can order specialty parts quickly."
    faq5q="Do you offer a pickup service?" ; faq5a="Yes, we collect and deliver vehicles across Dubai at your convenience."
    ctaSub="Book your Haval service with Dubai's trusted SUV specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Haval"
    relatedEn="gac-repair-dubai.html|GAC,chery-repair-dubai.html|Chery,geely-repair-dubai.html|Geely"
    titleAr="إصلاح هافال دبي | مركز خدمة هافال الإمارات"
    descAr="إصلاح وصيانة احترافية لسيارات هافال في دبي. فنيون مؤهلون وقطع غيار أصلية."
    heroSubAr="خدمة هافال الموثوقة من خبراء دبي"
    intro1Ar="توفر فيكس هايف إصلاحًا وصيانةً شاملةً لسيارات هافال في دبي."
    intro2Ar="فريقنا مدرب على محركات هافال التوربينية وعلب التروس المزدوجة."
    intro3Ar="نحتفظ بقطع غيار هافال الشائعة في المخزون."
    i1hAr="تشخيص هافال" ; i1pAr="أدوات مسح حديثة تغطي جميع وحدات التحكم."
    i2hAr="خدمة التوربو وDCT" ; i2pAr="صيانة متخصصة لمحركات 1.5T و2.0T وعلب التروس."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM أو معادلات معتمدة."
    i4hAr="رعاية نظام الدفع الرباعي" ; i4pAr="خدمة علبة نقل الحركة ومعايرة وضع التضاريس."
    faq1qAr="ما موديلات هافال التي تخدمونها؟" ; faq1aAr="جميع موديلات هافال بما فيها H6 وH9 وJolion وDargo."
    faq2qAr="كم مرة يجب صيانة سيارتي؟" ; faq2aAr="كل 10,000 كم أو 12 شهرًا."
    faq3qAr="هل تخدمون علبة تروس DCT؟" ; faq3aAr="نعم، لدينا فنيون متخصصون في أنظمة DCT."
    faq4qAr="هل تحتفظون بقطع غيار هافال؟" ; faq4aAr="نعم، نحتفظ بقطع التآكل الشائعة ونطلب الخاصة بسرعة."
    faq5qAr="هل تقدمون خدمة الاستلام؟" ; faq5aAr="نعم، نستلم ونسلم السيارات في جميع أنحاء دبي."
    ctaSubAr="احجز صيانة هافال مع متخصصي SUV في دبي."
  },
  @{
    slug="hongqi"; name="Hongqi"; nameAr="هونغقي"
    title="Hongqi Repair Dubai | Hongqi Service Centre UAE"
    desc="Expert Hongqi repair and servicing in Dubai. Specialist technicians, genuine parts, and advanced diagnostics for H5, H9, E-HS9 and all Hongqi models."
    models="H5, H9, HS5, HS7, E-HS9, EH7, L5"
    heroSub="Premium Hongqi Service in Dubai"
    intro1="FixHive provides specialist Hongqi service in Dubai for China's most prestigious automotive brand, maintaining the refinement your vehicle demands."
    intro2="Our technicians are trained on Hongqi's luxury powertrains and advanced electronic systems, providing accurate diagnostics and expert repairs."
    intro3="We source genuine Hongqi parts quickly to ensure lasting quality and the brand's premium standards are upheld."
    i1h="Hongqi Diagnostics" ; i1p="Specialist diagnostic tools access all Hongqi ECUs across the powertrain, chassis, and comfort systems."
    i2h="Luxury Powertrain" ; i2p="Expert care for Hongqi's V6 and V8 engines plus ZF automatic transmission service."
    i3h="Genuine Parts" ; i3p="Authentic Hongqi components sourced to maintain the premium quality of your vehicle."
    i4h="EV & Hybrid Support" ; i4p="Battery management, charging system diagnostics, and electric drivetrain care for Hongqi's EV range."
    faq1q="Which Hongqi models do you service?" ; faq1a="All Hongqi models including H5, H9, HS5, HS7, E-HS9, and EH7."
    faq2q="Can you source Hongqi parts in Dubai?" ; faq2a="Yes, we have established supply channels for genuine Hongqi parts with fast turnaround."
    faq3q="Do you service Hongqi electric vehicles?" ; faq3a="Yes, our EV-trained technicians handle Hongqi E-HS9 and EH7 battery and drivetrain systems."
    faq4q="How long does a Hongqi service take?" ; faq4a="Standard services are completed within a day; complex repairs are quoted individually."
    faq5q="Do you offer a pickup service?" ; faq5a="Yes, we collect and return your Hongqi across Dubai at your convenience."
    ctaSub="Book your Hongqi service with Dubai's premium car specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Hongqi"
    relatedEn="gac-repair-dubai.html|GAC,geely-repair-dubai.html|Geely,byd-repair-dubai.html|BYD"
    titleAr="إصلاح هونغقي دبي | مركز خدمة هونغقي الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات هونغقي في دبي. فنيون متخصصون وقطع غيار أصلية."
    heroSubAr="خدمة هونغقي المميزة في دبي"
    intro1Ar="تقدم فيكس هايف خدمة متخصصة لهونغقي في دبي."
    intro2Ar="فنيونا مدربون على أنظمة الدفع الفاخرة والإلكترونيات المتطورة."
    intro3Ar="نحصل على قطع هونغقي الأصلية بسرعة."
    i1hAr="تشخيص هونغقي" ; i1pAr="أدوات تشخيص متخصصة تصل إلى جميع وحدات التحكم."
    i2hAr="ناقل الحركة الفاخر" ; i2pAr="رعاية متخصصة لمحركات V6 وV8 وعلبة ZF."
    i3hAr="قطع غيار أصلية" ; i3pAr="مكونات هونغقي الأصيلة للحفاظ على جودة السيارة."
    i4hAr="دعم الكهربائي والهجين" ; i4pAr="إدارة البطارية وتشخيص نظام الشحن."
    faq1qAr="ما موديلات هونغقي التي تخدمونها؟" ; faq1aAr="جميع موديلات هونغقي بما فيها H5 وH9 وE-HS9."
    faq2qAr="هل يمكنكم توفير قطع هونغقي في دبي؟" ; faq2aAr="نعم، لدينا قنوات توريد راسخة لقطع هونغقي."
    faq3qAr="هل تخدمون سيارات هونغقي الكهربائية؟" ; faq3aAr="نعم، فنيونا متخصصون في أنظمة E-HS9 وEH7."
    faq4qAr="كم يستغرق صيانة هونغقي؟" ; faq4aAr="الصيانة القياسية تنتهي خلال يوم واحد."
    faq5qAr="هل تقدمون خدمة الاستلام؟" ; faq5aAr="نعم، نستلم ونعيد سيارتك في جميع أنحاء دبي."
    ctaSubAr="احجز صيانة هونغقي مع متخصصي السيارات الفاخرة في دبي."
  },
  @{
    slug="jeep"; name="Jeep"; nameAr="جيب"
    title="Jeep Repair Dubai | Jeep Service Centre UAE"
    desc="Expert Jeep repair and servicing in Dubai. Specialist off-road technicians, genuine parts, and full diagnostics for Wrangler, Grand Cherokee, Compass and all Jeep models."
    models="Wrangler, Grand Cherokee, Compass, Renegade, Gladiator, Cherokee, Commander"
    heroSub="Dubai's Off-Road Jeep Specialists"
    intro1="FixHive is Dubai's go-to Jeep specialist, delivering expert off-road repairs and maintenance for every Jeep in the lineup."
    intro2="Our technicians are skilled in Jeep's legendary 4x4 systems, solid axles, and lift kits — from stock Rubicons to highly modified overlanders."
    intro3="We use genuine Mopar parts and factory-specified procedures to keep your Jeep capable, reliable, and warranty-compliant."
    i1h="Jeep Diagnostics" ; i1p="wiTECH 2.0 and compatible tools cover all Jeep modules including SelecTrac, Rock-Trac, and Quadra-Drive."
    i2h="4x4 & Axle Service" ; i2p="Dana axle rebuilds, transfer case overhauls, locking differential service, and death-wobble correction."
    i3h="Lift Kits & Tyres" ; i3p="Suspension lifts, levelling kits, and large tyre fitment aligned and set up correctly for UAE roads."
    i4h="Engine & Gearbox" ; i4p="3.6L Pentastar V6, 3.0L EcoDiesel, and 2.0T engine service plus ZF 8-speed transmission care."
    faq1q="Do you fix Jeep Wrangler death wobble?" ; faq1a="Yes — we diagnose and correct death wobble by inspecting track bars, steering stabilisers, and worn components."
    faq2q="Can you install a lift kit on my Jeep?" ; faq2a="Yes, we fit and align lift kits, levelling kits, and oversize tyres on Jeep Wranglers and Grand Cherokees."
    faq3q="Which Jeep models do you service?" ; faq3a="All Jeep models — Wrangler, Grand Cherokee, Compass, Renegade, Gladiator, and more."
    faq4q="Do you use genuine Mopar parts?" ; faq4a="Yes, we use Mopar genuine parts and quality approved alternatives for all Jeep repairs."
    faq5q="Do you offer pickup and delivery?" ; faq5a="Yes, we collect and return your Jeep across Dubai at your convenience."
    ctaSub="Book your Jeep service with Dubai's off-road specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Jeep"
    relatedEn="land-rover-repair-dubai.html|Land Rover,dodge-repair-dubai.html|Dodge,chevrolet-repair-dubai.html|Chevrolet"
    titleAr="إصلاح جيب دبي | مركز خدمة جيب الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات جيب في دبي. فنيو طرق وعرة متخصصون وقطع غيار أصلية."
    heroSubAr="متخصصو جيب لطرق دبي الوعرة"
    intro1Ar="فيكس هايف هي الوجهة الأولى لإصلاح وصيانة جيب في دبي."
    intro2Ar="فنيونا متخصصون في أنظمة الدفع الرباعي والمحاور والرافعات."
    intro3Ar="نستخدم قطع Mopar الأصلية لضمان الكفاءة والموثوقية."
    i1hAr="تشخيص جيب" ; i1pAr="أدوات wiTECH 2.0 تغطي جميع وحدات جيب."
    i2hAr="خدمة 4×4 والمحاور" ; i2pAr="إعادة بناء محاور Dana وخدمة علبة نقل الحركة."
    i3hAr="رافعات وإطارات" ; i3pAr="تركيب رافعات التعليق وإطارات كبيرة مع ضبط الإطار الصحيح."
    i4hAr="المحرك وعلبة التروس" ; i4pAr="خدمة محركات Pentastar وEcoDiesel وناقل ZF."
    faq1qAr="هل تصلحون الاهتزاز في Wrangler؟" ; faq1aAr="نعم، نشخص ونصلح الاهتزاز بفحص قضبان التوجيه والمكونات البالية."
    faq2qAr="هل تركبون رافعات على جيب؟" ; faq2aAr="نعم، نركب رافعات التعليق والإطارات الكبيرة."
    faq3qAr="ما موديلات جيب التي تخدمونها؟" ; faq3aAr="جميع موديلات جيب بما فيها Wrangler وGrand Cherokee."
    faq4qAr="هل تستخدمون قطع Mopar الأصلية؟" ; faq4aAr="نعم، نستخدم قطع Mopar الأصلية."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نستلم ونعيد سيارتك في جميع أنحاء دبي."
    ctaSubAr="احجز صيانة جيب مع متخصصي الطرق الوعرة في دبي."
  },
  @{
    slug="jetour"; name="Jetour"; nameAr="جيتور"
    title="Jetour Repair Dubai | Jetour Service Centre UAE"
    desc="Professional Jetour repair and servicing in Dubai. Expert technicians, genuine parts, and full diagnostics for X70, X90, Dashing and all Jetour models."
    models="X70, X90, X95, Dashing, T2, X70 Plus, X90 Plus"
    heroSub="Reliable Jetour Service in Dubai"
    intro1="FixHive provides comprehensive Jetour repair and maintenance in Dubai, ensuring your Chery-engineered SUV stays in peak condition."
    intro2="Our technicians are familiar with Jetour's turbocharged platforms and electronic systems, delivering accurate diagnostics and reliable repairs."
    intro3="We stock common Jetour parts and can swiftly source specialist components to minimise your vehicle's time off the road."
    i1h="Jetour Diagnostics" ; i1p="Up-to-date scan tools cover all Jetour ECUs for fast and accurate fault identification."
    i2h="Turbo Engine Service" ; i2p="Full service for Jetour's 1.5T and 2.0T engines including oil systems, cooling, and air induction."
    i3h="Genuine Parts" ; i3p="OEM Jetour parts and approved alternatives maintain factory performance standards."
    i4h="Electrical & Safety" ; i4p="ADAS calibration, airbag system checks, and full electrical diagnostics for Jetour's connected SUVs."
    faq1q="Which Jetour models do you service?" ; faq1a="All Jetour models including X70, X90, X95, Dashing, and T2."
    faq2q="How often should my Jetour be serviced?" ; faq2a="Every 10,000 km or 12 months as recommended by the manufacturer."
    faq3q="Can you get Jetour spare parts in Dubai?" ; faq3a="Yes, we have reliable supply channels for genuine Jetour and compatible parts."
    faq4q="Do you reset Jetour service indicators?" ; faq4a="Yes, our diagnostic tools fully reset all Jetour service reminders and fault codes."
    faq5q="Do you offer a vehicle pickup service?" ; faq5a="Yes, we offer pickup and delivery across Dubai for your convenience."
    ctaSub="Book your Jetour service with Dubai's trusted specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Jetour"
    relatedEn="chery-repair-dubai.html|Chery,haval-repair-dubai.html|Haval,gac-repair-dubai.html|GAC"
    titleAr="إصلاح جيتور دبي | مركز خدمة جيتور الإمارات"
    descAr="إصلاح وصيانة احترافية لسيارات جيتور في دبي. فنيون خبراء وقطع غيار أصلية."
    heroSubAr="خدمة جيتور الموثوقة في دبي"
    intro1Ar="توفر فيكس هايف صيانة شاملة لسيارات جيتور في دبي."
    intro2Ar="فنيونا على دراية بمنصات جيتور التوربينية والأنظمة الإلكترونية."
    intro3Ar="نحتفظ بقطع جيتور الشائعة ونؤمن القطع الخاصة بسرعة."
    i1hAr="تشخيص جيتور" ; i1pAr="أدوات مسح حديثة لتشخيص جميع وحدات التحكم."
    i2hAr="خدمة المحرك التوربيني" ; i2pAr="صيانة كاملة لمحركات 1.5T و2.0T."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM أو معادلات معتمدة."
    i4hAr="الكهرباء والسلامة" ; i4pAr="معايرة ADAS وفحص أنظمة الوسائد الهوائية."
    faq1qAr="ما موديلات جيتور التي تخدمونها؟" ; faq1aAr="جميع موديلات جيتور بما فيها X70 وX90 وDashing."
    faq2qAr="كم مرة يجب صيانة سيارتي؟" ; faq2aAr="كل 10,000 كم أو 12 شهرًا."
    faq3qAr="هل يمكنكم الحصول على قطع جيتور؟" ; faq3aAr="نعم، لدينا قنوات موثوقة لقطع جيتور."
    faq4qAr="هل تعيدون ضبط مؤشرات الخدمة؟" ; faq4aAr="نعم، تعيد أدواتنا ضبط جميع تذكيرات الخدمة."
    faq5qAr="هل تقدمون خدمة الاستلام؟" ; faq5aAr="نعم، نقدم الاستلام والتسليم في جميع أنحاء دبي."
    ctaSubAr="احجز صيانة جيتور مع متخصصي دبي الموثوقين."
  },
  @{
    slug="lamborghini"; name="Lamborghini"; nameAr="لامبورغيني"
    title="Lamborghini Repair Dubai | Expert Lamborghini Service UAE"
    desc="Specialist Lamborghini repair in Dubai. Expert technicians, genuine parts, and precision diagnostics for Urus, Huracan, Aventador and all Lamborghini models."
    models="Urus, Urus S, Huracán EVO, Huracán Sterrato, Aventador S, Revuelto"
    heroSub="Raging Bull Precision — Dubai's Lamborghini Experts"
    intro1="FixHive delivers the level of precision Lamborghini engineering demands, with specialist technicians trained on Sant'Agata's most exhilarating machines."
    intro2="From naturally aspirated V10s and V12s to the turbocharged Urus SUV, our team has the expertise and tools to keep every Lamborghini at its best."
    intro3="Genuine parts, factory-specified procedures, and a passion for performance define every Lamborghini repair at FixHive."
    i1h="Lamborghini Diagnostics" ; i1p="Factory-level diagnostic tools read every Lamborghini module — engine, gearbox, chassis, and LDVI system."
    i2h="V10 & V12 Engines" ; i2p="Expert care for Lamborghini's naturally aspirated masterpieces and the twin-turbo Urus powertrain."
    i3h="Genuine Parts" ; i3p="OEM Lamborghini parts and approved components maintain the performance and value of your supercar."
    i4h="Urus SUV Specialist" ; i4p="Full Urus service including air suspension, quattro AWD, and twin-turbo V8 engine maintenance."
    faq1q="Do you service all Lamborghini models?" ; faq1a="Yes — Urus, Huracán, Aventador, Revuelto, and all previous models."
    faq2q="How long does a Lamborghini service take?" ; faq2a="A standard annual service typically takes one to two days; complex work is quoted in advance."
    faq3q="Do you use genuine Lamborghini parts?" ; faq3a="Yes, all parts are OEM Lamborghini or manufacturer-approved alternatives."
    faq4q="Can you service the Lamborghini Urus air suspension?" ; faq4a="Yes, our technicians are trained on the Urus's advanced air suspension and electric systems."
    faq5q="Do you offer collection and delivery?" ; faq5a="Yes, we offer white-glove collection and delivery for all Lamborghini customers in Dubai."
    ctaSub="Book your Lamborghini service with Dubai's supercar specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Lamborghini"
    relatedEn="ferrari-repair-dubai.html|Ferrari,maserati-repair-dubai.html|Maserati,porsche-repair-dubai.html|Porsche"
    titleAr="إصلاح لامبورغيني دبي | خدمة لامبورغيني المتخصصة"
    descAr="إصلاح لامبورغيني المتخصص في دبي. فنيون خبراء وقطع غيار أصلية لجميع موديلات لامبورغيني."
    heroSubAr="دقة الثور الهائج — خبراء لامبورغيني في دبي"
    intro1Ar="تقدم فيكس هايف مستوى الدقة الذي تتطلبه هندسة لامبورغيني."
    intro2Ar="من محركات V10 وV12 الطبيعية إلى Urus التوربينية، فريقنا لديه الخبرة والأدوات."
    intro3Ar="قطع أصلية وإجراءات المصنع وشغف بالأداء في كل إصلاح."
    i1hAr="تشخيص لامبورغيني" ; i1pAr="أدوات تشخيص على مستوى المصنع لكل وحدة تحكم."
    i2hAr="محركات V10 وV12" ; i2pAr="رعاية متخصصة لتحف لامبورغيني الطبيعية وناقل Urus."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM لامبورغيني للحفاظ على الأداء والقيمة."
    i4hAr="متخصص Urus SUV" ; i4pAr="خدمة Urus الكاملة بما فيها التعليق الهوائي ومحرك V8."
    faq1qAr="هل تخدمون جميع موديلات لامبورغيني؟" ; faq1aAr="نعم، Urus وHuracán وAventador وRevuelto وجميع الموديلات."
    faq2qAr="كم يستغرق صيانة لامبورغيني؟" ; faq2aAr="الصيانة القياسية تستغرق يومًا إلى يومين."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، جميع القطع OEM أو معتمدة من المصنع."
    faq4qAr="هل تخدمون التعليق الهوائي لـ Urus؟" ; faq4aAr="نعم، فنيونا مدربون على أنظمة Urus المتطورة."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم خدمة استلام وتسليم فاخرة."
    ctaSubAr="احجز صيانة لامبورغيني مع متخصصي السيارات الفائقة في دبي."
  },
  @{
    slug="lincoln"; name="Lincoln"; nameAr="لينكولن"
    title="Lincoln Repair Dubai | Lincoln Service Centre UAE"
    desc="Expert Lincoln repair and servicing in Dubai. Specialist technicians, genuine parts, and full diagnostics for Navigator, Aviator, Corsair and all Lincoln models."
    models="Navigator, Aviator, Corsair, Nautilus, Continental, MKZ"
    heroSub="American Luxury Maintained to Perfection"
    intro1="FixHive provides specialist Lincoln repair and maintenance in Dubai, preserving the quiet luxury and advanced technology your vehicle offers."
    intro2="Our technicians are trained on Lincoln's air suspension, twin-turbo engines, and co-pilot360 safety systems for complete peace of mind."
    intro3="Using genuine Ford-Lincoln parts and approved alternatives, every repair is completed to factory specification and fully documented."
    i1h="Lincoln Diagnostics" ; i1p="IDS-compatible tools cover all Lincoln modules including air suspension, PEPS, and driver-assistance systems."
    i2h="Navigator & Aviator Service" ; i2p="Full service for Lincoln's flagship SUVs, including EcoBoost V6 engines and 10-speed transmission."
    i3h="Air Suspension" ; i3p="Diagnosis and repair of Lincoln's PerfectPosition air suspension for the smoothest possible ride."
    i4h="Genuine Parts" ; i4p="Ford-Lincoln OEM parts and quality alternatives maintain warranty compliance and long-term reliability."
    faq1q="Which Lincoln models do you service?" ; faq1a="All Lincoln models — Navigator, Aviator, Corsair, Nautilus, Continental, and more."
    faq2q="Can you fix Lincoln air suspension?" ; faq2a="Yes, we diagnose and repair Lincoln's air suspension compressors, airbags, and control modules."
    faq3q="Do you use genuine Lincoln parts?" ; faq3a="Yes, we use genuine Ford-Lincoln OEM parts and approved quality alternatives."
    faq4q="How often should my Lincoln be serviced?" ; faq4a="Every 10,000 km or 12 months, or as indicated by the Intelligent Oil-Life Monitor."
    faq5q="Do you offer pickup and delivery?" ; faq5a="Yes, we collect and return Lincoln vehicles across Dubai at your convenience."
    ctaSub="Book your Lincoln service with Dubai's American luxury specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Lincoln"
    relatedEn="cadillac-repair-dubai.html|Cadillac,ford-repair-dubai.html|Ford,gmc-repair-dubai.html|GMC"
    titleAr="إصلاح لينكولن دبي | مركز خدمة لينكولن الإمارات"
    descAr="إصلاح وصيانة متخصصة لسيارات لينكولن في دبي. فنيون متخصصون وقطع غيار أصلية."
    heroSubAr="الفخامة الأمريكية محفوظة للكمال"
    intro1Ar="تقدم فيكس هايف إصلاحًا وصيانةً متخصصةً للينكولن في دبي."
    intro2Ar="فنيونا مدربون على التعليق الهوائي ومحركات التوربو وأنظمة co-pilot360."
    intro3Ar="باستخدام قطع Ford-Lincoln الأصلية، كل إصلاح يتم وفق مواصفات المصنع."
    i1hAr="تشخيص لينكولن" ; i1pAr="أدوات متوافقة مع IDS تغطي جميع وحدات لينكولن."
    i2hAr="خدمة Navigator وAviator" ; i2pAr="خدمة كاملة لسيارات SUV الرائدة بما فيها محرك EcoBoost."
    i3hAr="التعليق الهوائي" ; i3pAr="تشخيص وإصلاح نظام PerfectPosition لأسلس ركوب."
    i4hAr="قطع غيار أصلية" ; i4pAr="قطع Ford-Lincoln OEM للامتثال للضمان والموثوقية."
    faq1qAr="ما موديلات لينكولن التي تخدمونها؟" ; faq1aAr="جميع موديلات لينكولن بما فيها Navigator وAviator."
    faq2qAr="هل تصلحون التعليق الهوائي؟" ; faq2aAr="نعم، نشخص ونصلح ضاغط التعليق الهوائي ووحدات التحكم."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، نستخدم قطع Ford-Lincoln OEM الأصلية."
    faq4qAr="كم مرة يجب صيانة لينكولن؟" ; faq4aAr="كل 10,000 كم أو 12 شهرًا."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نستلم ونعيد سيارات لينكولن في جميع أنحاء دبي."
    ctaSubAr="احجز صيانة لينكولن مع متخصصي الفخامة الأمريكية في دبي."
  },
  @{
    slug="maserati"; name="Maserati"; nameAr="مازيراتي"
    title="Maserati Repair Dubai | Expert Maserati Service UAE"
    desc="Specialist Maserati repair in Dubai. Certified technicians, genuine parts, and precision diagnostics for Ghibli, Quattroporte, Levante, GranTurismo and all Maserati models."
    models="Ghibli, Quattroporte, Levante, GranTurismo, Grecale, MC20"
    heroSub="Italian Excellence — Dubai's Maserati Specialists"
    intro1="FixHive provides factory-standard Maserati repair in Dubai, combining Italian engineering know-how with world-class workshop facilities."
    intro2="Our technicians are trained on Maserati's twin-turbo V6 and V8 powertrains, ZF gearboxes, and advanced chassis electronics."
    intro3="Genuine Maserati parts, manufacturer-specified fluids, and meticulous craftsmanship define every repair at FixHive."
    i1h="Maserati Diagnostics" ; i1p="MDIS-compatible tools cover all Maserati modules — engine, transmission, air suspension, and ADAS."
    i2h="V6 & V8 Engines" ; i2p="Expert care for Maserati's Nettuno, 3.0 V6, and 3.8 V8 twin-turbo engines."
    i3h="ZF Gearbox Service" ; i3p="ZF 8-speed automatic and 8-speed DCT service, calibration, and repair."
    i4h="Genuine Parts" ; i4p="OEM Maserati components and approved alternatives maintain trident performance and residual value."
    faq1q="Do you service all Maserati models?" ; faq1a="Yes — Ghibli, Quattroporte, Levante, GranTurismo, Grecale, and MC20."
    faq2q="How long does a Maserati service take?" ; faq2a="Standard annual services take one to two days; complex repairs are quoted individually."
    faq3q="Can you fix Maserati air suspension?" ; faq3a="Yes, we diagnose and repair Levante and Quattroporte air suspension systems."
    faq4q="Do you use genuine Maserati parts?" ; faq4a="Yes, all repairs use OEM Maserati parts or manufacturer-approved alternatives."
    faq5q="Do you offer collection and delivery?" ; faq5a="Yes, we offer premium collection and delivery across Dubai for all Maserati customers."
    ctaSub="Book your Maserati service with Dubai's Italian supercar specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Maserati"
    relatedEn="ferrari-repair-dubai.html|Ferrari,lamborghini-repair-dubai.html|Lamborghini,porsche-repair-dubai.html|Porsche"
    titleAr="إصلاح مازيراتي دبي | خدمة مازيراتي المتخصصة"
    descAr="إصلاح مازيراتي المتخصص في دبي. فنيون معتمدون وقطع غيار أصلية لجميع الموديلات."
    heroSubAr="التميز الإيطالي — متخصصو مازيراتي في دبي"
    intro1Ar="تقدم فيكس هايف إصلاح مازيراتي بمعايير المصنع في دبي."
    intro2Ar="فنيونا مدربون على محركات التوربو V6 وV8 وعلب ZF والإلكترونيات."
    intro3Ar="قطع أصلية وسوائل محددة من المصنع في كل إصلاح."
    i1hAr="تشخيص مازيراتي" ; i1pAr="أدوات MDIS تغطي جميع وحدات مازيراتي."
    i2hAr="محركات V6 وV8" ; i2pAr="رعاية متخصصة لمحركات Nettuno والتوربو المزدوج."
    i3hAr="خدمة علبة ZF" ; i3pAr="خدمة ومعايرة وإصلاح علب ZF."
    i4hAr="قطع غيار أصلية" ; i4pAr="قطع OEM مازيراتي للحفاظ على الأداء والقيمة."
    faq1qAr="هل تخدمون جميع موديلات مازيراتي؟" ; faq1aAr="نعم، Ghibli وQuattroporte وLevante وGranTurismo وGrecale."
    faq2qAr="كم يستغرق صيانة مازيراتي؟" ; faq2aAr="الصيانة القياسية تستغرق يومًا إلى يومين."
    faq3qAr="هل تصلحون التعليق الهوائي؟" ; faq3aAr="نعم، نشخص ونصلح أنظمة Levante وQuattroporte."
    faq4qAr="هل تستخدمون قطع أصلية؟" ; faq4aAr="نعم، جميع الإصلاحات تستخدم قطع OEM أو معتمدة."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم استلامًا وتسليمًا فاخرًا لعملاء مازيراتي."
    ctaSubAr="احجز صيانة مازيراتي مع متخصصي السيارات الإيطالية في دبي."
  },
  @{
    slug="maybach"; name="Mercedes-Maybach"; nameAr="مرسيدس-مايباخ"
    title="Mercedes-Maybach Repair Dubai | Maybach Service UAE"
    desc="Ultra-luxury Mercedes-Maybach repair in Dubai. Elite technicians, genuine AMG parts, and white-glove service for Maybach S-Class, GLS, and EQS models."
    models="Maybach S 580, S 680, GLS 600, EQS 680, Maybach SL 680"
    heroSub="The Pinnacle of Luxury — Dubai's Maybach Specialists"
    intro1="FixHive provides the discreet, ultra-luxury service that Mercedes-Maybach ownership demands — meticulous, private, and to the highest standard."
    intro2="Our elite technicians are trained on Maybach's bespoke V8 and V12 powertrains, rear-axle steering, and Burmester sound systems."
    intro3="Every Maybach repair uses genuine Mercedes-Benz OEM parts, specialist fluids, and documented procedures to preserve extraordinary residual value."
    i1h="Maybach Diagnostics" ; i1p="Mercedes XENTRY diagnostic suite covers every Maybach system — from the biturbo V12 to the rear-cabin entertainment."
    i2h="V8 & V12 Engines" ; i2p="Expert care for Maybach's M276, M176, and M297 engines with factory-specification service intervals."
    i3h="Rear-Axle Steering" ; i3p="Calibration and repair of Maybach's rear-wheel steering for ultra-smooth low-speed manoeuvrability."
    i4h="White-Glove Service" ; i4p="Fully documented service history, premium detailing, and discreet handling for every Maybach."
    faq1q="Which Maybach models do you service?" ; faq1a="All Mercedes-Maybach models — S 580, S 680, GLS 600, EQS 680, and SL 680."
    faq2q="How long does a Maybach service take?" ; faq2a="Standard annual service takes one to two days; complex work is quoted case by case."
    faq3q="Do you use genuine Mercedes-Maybach parts?" ; faq3a="Yes, exclusively OEM Mercedes-Benz parts are used to maintain Maybach standards."
    faq4q="Can you service the Maybach V12 engine?" ; faq4a="Yes, our technicians are trained on Mercedes' AMG 6.0L M297 V12 biturbo engine."
    faq5q="Do you offer collection and delivery?" ; faq5a="Yes, we offer fully discreet white-glove collection and delivery across Dubai."
    ctaSub="Book your Maybach service with Dubai's ultra-luxury specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Mercedes-Maybach"
    relatedEn="mercedes-benz-repair-dubai.html|Mercedes-Benz,rolls-royce-repair-dubai.html|Rolls-Royce,bentley-repair-dubai.html|Bentley"
    titleAr="إصلاح مرسيدس-مايباخ دبي | خدمة مايباخ الإمارات"
    descAr="إصلاح مرسيدس-مايباخ الفاخر في دبي. فنيون نخبويون وقطع غيار أصلية وخدمة VIP."
    heroSubAr="قمة الفخامة — متخصصو مايباخ في دبي"
    intro1Ar="تقدم فيكس هايف الخدمة السرية الفاخرة التي يتطلبها امتلاك مايباخ."
    intro2Ar="فنيونا النخبويون مدربون على محركات V8 وV12 الخاصة بمايباخ."
    intro3Ar="كل إصلاح يستخدم قطع Mercedes-Benz OEM وسوائل متخصصة."
    i1hAr="تشخيص مايباخ" ; i1pAr="نظام Mercedes XENTRY يغطي كل نظام في مايباخ."
    i2hAr="محركات V8 وV12" ; i2pAr="رعاية متخصصة لمحركات M276 وM176 وM297."
    i3hAr="التوجيه بالمحور الخلفي" ; i3pAr="معايرة وإصلاح نظام التوجيه بالعجلات الخلفية."
    i4hAr="خدمة VIP" ; i4pAr="سجل خدمة موثق وتفصيل فاخر وتعامل سري."
    faq1qAr="ما موديلات مايباخ التي تخدمونها؟" ; faq1aAr="جميع موديلات Mercedes-Maybach بما فيها S 580 وS 680 وGLS 600."
    faq2qAr="كم يستغرق صيانة مايباخ؟" ; faq2aAr="الصيانة القياسية تستغرق يومًا إلى يومين."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، نستخدم حصريًا قطع Mercedes-Benz OEM."
    faq4qAr="هل تخدمون محرك V12 لمايباخ؟" ; faq4aAr="نعم، فنيونا مدربون على محرك AMG 6.0L M297 V12."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم استلامًا وتسليمًا سريًا فاخرًا في دبي."
    ctaSubAr="احجز صيانة مايباخ مع متخصصي الفخامة الفائقة في دبي."
  },
  @{
    slug="mg"; name="MG"; nameAr="إم جي"
    title="MG Repair Dubai | MG Service Centre UAE"
    desc="Professional MG repair and servicing in Dubai. Expert technicians, genuine parts, and full diagnostics for ZS, HS, RX5, MG5 and all MG models including EVs."
    models="ZS, ZS EV, HS, MG5, RX5, MG4 EV, Cyberster"
    heroSub="Modern MG Service for Dubai's Roads"
    intro1="FixHive provides comprehensive MG repair and maintenance in Dubai for one of the fastest-growing brands on UAE roads."
    intro2="Our technicians are trained on MG's petrol, hybrid, and electric powertrains, delivering accurate diagnostics and efficient repairs."
    intro3="We stock common MG parts and can source specialist items quickly, minimising downtime and keeping your MG on the road."
    i1h="MG Diagnostics" ; i1p="SAIC-certified scan tools cover all MG ECUs including the MG Pilot ADAS suite and EV battery modules."
    i2h="MG EV Service" ; i2p="Specialist EV care for ZS EV and MG4, including battery health checks and charging system diagnostics."
    i3h="Genuine Parts" ; i3p="OEM MG parts and approved alternatives keep your vehicle performing to factory spec."
    i4h="Turbo & DCT" ; i4p="Service for MG's 1.5T and 2.0T turbocharged engines and 7-speed dual-clutch transmission."
    faq1q="Which MG models do you service?" ; faq1a="All MG models — ZS, ZS EV, HS, MG5, MG4 EV, RX5, and Cyberster."
    faq2q="Can you service MG electric vehicles?" ; faq2a="Yes, our EV technicians service ZS EV and MG4 battery, motor, and charging systems."
    faq3q="How often should my MG be serviced?" ; faq3a="Every 10,000 km or 12 months for petrol models; EVs follow MG's maintenance schedule."
    faq4q="Do you use genuine MG parts?" ; faq4a="Yes, we use genuine SAIC-MG parts and approved quality alternatives."
    faq5q="Do you offer a vehicle pickup service?" ; faq5a="Yes, we offer pickup and delivery across Dubai at your convenience."
    ctaSub="Book your MG service with Dubai's trusted specialists today."
    waMsg="Hi FixHive, I need a service/repair for my MG"
    relatedEn="geely-repair-dubai.html|Geely,chery-repair-dubai.html|Chery,byd-repair-dubai.html|BYD"
    titleAr="إصلاح إم جي دبي | مركز خدمة إم جي الإمارات"
    descAr="إصلاح وصيانة احترافية لسيارات إم جي في دبي. فنيون خبراء وقطع غيار أصلية."
    heroSubAr="خدمة إم جي الحديثة لطرق دبي"
    intro1Ar="توفر فيكس هايف صيانة شاملة لسيارات إم جي في دبي."
    intro2Ar="فنيونا مدربون على أنظمة إم جي البنزينية والهجينة والكهربائية."
    intro3Ar="نحتفظ بقطع إم جي الشائعة ونؤمن الخاصة بسرعة."
    i1hAr="تشخيص إم جي" ; i1pAr="أدوات مسح SAIC تغطي جميع وحدات التحكم."
    i2hAr="خدمة إم جي الكهربائية" ; i2pAr="رعاية متخصصة للسيارات الكهربائية ZS EV وMG4."
    i3hAr="قطع غيار أصلية" ; i3pAr="قطع OEM إم جي ومعادلات معتمدة."
    i4hAr="التوربو وDCT" ; i4pAr="خدمة محركات 1.5T و2.0T وعلبة التروس المزدوجة."
    faq1qAr="ما موديلات إم جي التي تخدمونها؟" ; faq1aAr="جميع موديلات إم جي بما فيها ZS وHS وMG4 وMG5."
    faq2qAr="هل تخدمون سيارات إم جي الكهربائية؟" ; faq2aAr="نعم، نخدم البطارية والمحرك ونظام الشحن لـ ZS EV وMG4."
    faq3qAr="كم مرة يجب صيانة سيارتي؟" ; faq3aAr="كل 10,000 كم أو 12 شهرًا للبنزين."
    faq4qAr="هل تستخدمون قطع أصلية؟" ; faq4aAr="نعم، نستخدم قطع SAIC-MG الأصلية."
    faq5qAr="هل تقدمون خدمة الاستلام؟" ; faq5aAr="نعم، نقدم الاستلام والتسليم في دبي."
    ctaSubAr="احجز صيانة إم جي مع متخصصي دبي الموثوقين."
  },
  @{
    slug="ram"; name="RAM"; nameAr="رام"
    title="RAM Truck Repair Dubai | RAM Service Centre UAE"
    desc="Expert RAM truck repair and servicing in Dubai. Specialist technicians, genuine Mopar parts, and full diagnostics for RAM 1500, 2500, 3500 and all RAM trucks."
    models="RAM 1500, RAM 1500 TRX, RAM 2500, RAM 3500, RAM 1500 Classic, ProMaster"
    heroSub="Dubai's RAM Truck Specialists"
    intro1="FixHive is Dubai's trusted RAM truck specialist, delivering expert repairs and maintenance for every RAM pickup in the lineup."
    intro2="Our technicians are highly skilled in RAM's HEMI V8 and EcoDiesel powertrains, air suspension, and heavy-duty towing systems."
    intro3="Genuine Mopar parts, FCA-specified procedures, and a passion for capability define every RAM repair at FixHive."
    i1h="RAM Diagnostics" ; i1p="wiTECH 2.0 tools provide full coverage of RAM's modules including eTorque, air suspension, and 4WD."
    i2h="HEMI & EcoDiesel" ; i2p="Expert service for RAM's 5.7L HEMI, 6.2L supercharged TRX, and 3.0L EcoDiesel engines."
    i3h="4WD & Towing" ; i3p="Transfer case service, trailer brake controller calibration, and heavy-duty driveline maintenance."
    i4h="Air Suspension" ; i4p="Diagnosis and repair of RAM's coil-spring and optional active-level air suspension systems."
    faq1q="Which RAM models do you service?" ; faq1a="All RAM trucks — 1500, 1500 TRX, 2500, 3500, Classic, and ProMaster."
    faq2q="Can you service the RAM TRX supercharger?" ; faq2a="Yes, our technicians are trained on the 6.2L supercharged HEMI in the RAM 1500 TRX."
    faq3q="Do you use genuine Mopar parts?" ; faq3a="Yes, all RAM repairs use genuine Mopar parts or approved quality alternatives."
    faq4q="Can you fix RAM air suspension?" ; faq4a="Yes, we diagnose and repair RAM's active air suspension compressors and bags."
    faq5q="Do you offer pickup and delivery?" ; faq5a="Yes, we collect and deliver RAM trucks across Dubai at your convenience."
    ctaSub="Book your RAM truck service with Dubai's pickup specialists today."
    waMsg="Hi FixHive, I need a service/repair for my RAM Truck"
    relatedEn="dodge-repair-dubai.html|Dodge,gmc-repair-dubai.html|GMC,jeep-repair-dubai.html|Jeep"
    titleAr="إصلاح شاحنات رام دبي | مركز خدمة رام الإمارات"
    descAr="إصلاح وصيانة متخصصة لشاحنات رام في دبي. فنيون متخصصون وقطع Mopar أصلية."
    heroSubAr="متخصصو شاحنات رام في دبي"
    intro1Ar="فيكس هايف هي المتخصص الموثوق لشاحنات رام في دبي."
    intro2Ar="فنيونا ماهرون في محركات HEMI V8 وEcoDiesel وأنظمة التعليق الهوائي."
    intro3Ar="قطع Mopar الأصلية وإجراءات FCA في كل إصلاح."
    i1hAr="تشخيص رام" ; i1pAr="أدوات wiTECH 2.0 تغطي جميع وحدات رام."
    i2hAr="محركات HEMI وEcoDiesel" ; i2pAr="خدمة متخصصة لمحركات 5.7L HEMI و6.2L TRX و3.0L EcoDiesel."
    i3hAr="الدفع الرباعي والجر" ; i3pAr="خدمة علبة نقل الحركة ومعايرة وحدة فرامل المقطورة."
    i4hAr="التعليق الهوائي" ; i4pAr="تشخيص وإصلاح أنظمة التعليق الهوائي."
    faq1qAr="ما موديلات رام التي تخدمونها؟" ; faq1aAr="جميع شاحنات رام بما فيها 1500 وTRX و2500 و3500."
    faq2qAr="هل تخدمون ضاغط TRX؟" ; faq2aAr="نعم، فنيونا مدربون على محرك 6.2L HEMI المضغوط."
    faq3qAr="هل تستخدمون قطع Mopar الأصلية؟" ; faq3aAr="نعم، جميع إصلاحات رام تستخدم قطع Mopar."
    faq4qAr="هل تصلحون التعليق الهوائي؟" ; faq4aAr="نعم، نشخص ونصلح ضاغط التعليق الهوائي."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نستلم ونعيد شاحنات رام في دبي."
    ctaSubAr="احجز صيانة شاحنتك رام مع متخصصي دبي."
  },
  @{
    slug="rolls-royce"; name="Rolls-Royce"; nameAr="رولز رويس"
    title="Rolls-Royce Repair Dubai | Rolls-Royce Service UAE"
    desc="Ultra-exclusive Rolls-Royce repair in Dubai. Elite technicians, genuine parts, and bespoke service for Ghost, Phantom, Cullinan, Wraith and all Rolls-Royce models."
    models="Ghost, Phantom, Cullinan, Wraith, Dawn, Spectre EV"
    heroSub="The Spirit of Ecstasy — Maintained in Dubai"
    intro1="FixHive provides the extraordinary level of care that Rolls-Royce ownership demands — meticulous, discreet, and uncompromisingly excellent."
    intro2="Our elite technicians are trained on Rolls-Royce's bespoke V12 and twin-turbo powertrains, self-levelling air suspension, and Starlight headliner systems."
    intro3="Every Rolls-Royce repair uses genuine BMW-Rolls-Royce OEM parts, specialist lubricants, and fully documented service history to preserve ultimate residual value."
    i1h="Rolls-Royce Diagnostics" ; i1p="BMW ISTA and specialist tools provide complete diagnostic coverage of every Rolls-Royce system."
    i2h="V12 & Biturbo V12" ; i2p="Expert service for Rolls-Royce's N74 6.75L biturbo V12, the Phantom's 6.75L, and Spectre's EV drivetrain."
    i3h="Air Suspension" ; i3p="Precision calibration and repair of Rolls-Royce's Magic Carpet Ride self-levelling air suspension."
    i4h="Bespoke Detailing" ; i4p="White-glove interior and exterior care, maintaining every bespoke element of your Rolls-Royce."
    faq1q="Which Rolls-Royce models do you service?" ; faq1a="All Rolls-Royce models — Ghost, Phantom, Cullinan, Wraith, Dawn, and Spectre EV."
    faq2q="How long does a Rolls-Royce service take?" ; faq2a="Standard annual service takes one to two days with pre-arranged white-glove handling."
    faq3q="Do you use genuine Rolls-Royce parts?" ; faq3a="Yes, exclusively genuine BMW-Rolls-Royce OEM parts and specialist fluids are used."
    faq4q="Can you service the Rolls-Royce Spectre EV?" ; faq4a="Yes, our EV-trained technicians handle the Spectre's 102 kWh battery and dual-motor system."
    faq5q="Do you offer collection and delivery?" ; faq5a="Yes, fully discreet white-glove collection and delivery is available across Dubai and the UAE."
    ctaSub="Book your Rolls-Royce service with Dubai's ultra-luxury specialists today."
    waMsg="Hi FixHive, I need a service/repair for my Rolls-Royce"
    relatedEn="bentley-repair-dubai.html|Bentley,maybach-repair-dubai.html|Mercedes-Maybach,aston-martin-repair-dubai.html|Aston Martin"
    titleAr="إصلاح رولز رويس دبي | خدمة رولز رويس الإمارات"
    descAr="إصلاح رولز رويس الحصري في دبي. فنيون نخبويون وقطع غيار أصلية وخدمة بيسبوك."
    heroSubAr="روح النشوة — محفوظة في دبي"
    intro1Ar="تقدم فيكس هايف مستوى الرعاية الاستثنائي الذي يتطلبه امتلاك رولز رويس."
    intro2Ar="فنيونا مدربون على محركات V12 التوربينية ونظام التعليق الهوائي."
    intro3Ar="كل إصلاح يستخدم قطع BMW-Rolls-Royce OEM وزيوت متخصصة."
    i1hAr="تشخيص رولز رويس" ; i1pAr="BMW ISTA وأدوات متخصصة لتغطية كاملة."
    i2hAr="محرك V12 الثنائي التوربو" ; i2pAr="خدمة متخصصة لمحرك 6.75L N74 ومحرك Spectre الكهربائي."
    i3hAr="التعليق الهوائي" ; i3pAr="معايرة وإصلاح نظام Magic Carpet Ride."
    i4hAr="تفصيل بيسبوك" ; i4pAr="رعاية داخلية وخارجية فائقة لكل عنصر بيسبوك."
    faq1qAr="ما موديلات رولز رويس التي تخدمونها؟" ; faq1aAr="Ghost وPhantom وCullinan وWraith وDawn وSpectre EV."
    faq2qAr="كم يستغرق صيانة رولز رويس؟" ; faq2aAr="الصيانة القياسية تستغرق يومًا إلى يومين."
    faq3qAr="هل تستخدمون قطع أصلية؟" ; faq3aAr="نعم، حصريًا قطع BMW-Rolls-Royce OEM وزيوت متخصصة."
    faq4qAr="هل تخدمون Spectre الكهربائية؟" ; faq4aAr="نعم، فنيونا يتعاملون مع بطارية Spectre ومحركيها المزدوجين."
    faq5qAr="هل تقدمون الاستلام والتسليم؟" ; faq5aAr="نعم، نقدم استلامًا وتسليمًا سريًا فاخرًا في دبي والإمارات."
    ctaSubAr="احجز صيانة رولز رويس مع متخصصي الفخامة الفائقة في دبي."
  }
)

$root = "C:\Users\gianl\OneDrive\Desktop\AI\fixhive"

foreach ($b in $brands3) {
  $enPath = Join-Path $root "$($b.slug)-repair-dubai.html"
  $arPath = Join-Path $root "ar\$($b.slug)-repair-dubai.html"
  $en = New-ENPage $b
  $ar = New-ARPage $b
  [System.IO.File]::WriteAllText($enPath, $en, [System.Text.Encoding]::UTF8)
  [System.IO.File]::WriteAllText($arPath, $ar, [System.Text.Encoding]::UTF8)
  Write-Host "  Created: $($b.slug)-repair-dubai.html + ar/"
}

Write-Host ""
Write-Host "gen-brands-3.ps1 complete — $($brands3.Count) brands x 2 pages = $($brands3.Count * 2) files generated."
