# Brand page generator for FixHive
# Generates EN + AR pages for 24 brands

$rootDir = "C:\Users\gianl\OneDrive\Desktop\AI\fixhive"

# -----------------------------------------------------------------------
# Brand data: slug, display name, models subtitle, hero subtext,
#             intro (4 paragraphs), 4 issues, 5 FAQs, CTA text,
#             WhatsApp message
# -----------------------------------------------------------------------

$brands = @(

  @{
    slug = "aston-martin"
    name = "Aston Martin"
    models = "DB11 · Vantage · DBX · DBS · Vanquish"
    heroSub = "Dubai's specialist for Aston Martin DB11, Vantage, DBX, DBS and Vanquish. Hand-built British grand tourers deserve expert care from technicians who understand their unique engineering."
    intro = @(
      "Aston Martin occupies a singular position in the automotive world — a small, independent British manufacturer producing hand-crafted grand tourers and sports cars that blend extraordinary performance with bespoke elegance. In Dubai, the Aston Martin is a statement of refined taste rather than mere wealth, and owners expect their cars to perform flawlessly in a climate that was never part of the original engineering brief. The DBX, Aston Martin's first SUV, has significantly expanded the brand's presence in the UAE market, bringing first-time Aston Martin owners who may not be familiar with the brand's specific maintenance requirements.",
      "Every Aston Martin sold in the UAE is built around a hand-assembled Mercedes-AMG derived V8 or a bespoke twin-turbocharged V12. These engines are calibrated for performance and refinement above all else, and they demand lubricants, fluids and service intervals that reflect this priority. In Dubai's ambient temperatures of 45°C or above, the cooling and lubrication demands on these high-output engines are extreme. Oil temperature management is particularly critical — synthetic lubricants must be renewed on schedule, and the engine's dry-sump system requires careful inspection at every service.",
      "The DBX uses an AMG-derived 4.0-litre twin-turbo V8 producing 550 hp, mated to a nine-speed automatic transmission. In Dubai, this platform faces the same thermal challenges as its AMG counterparts but with additional complexity from Aston Martin's own chassis tuning software and adaptive suspension systems. The sports cars — DB11, Vantage and DBS — sit lower and run hotter; in summer traffic their cooling systems operate near design limits for extended periods, making thermostat condition, coolant quality and radiator integrity critical safety items.",
      "At FixHive, our technicians have experience with Aston Martin's AMG-derived platforms as well as the older V8 Vantage and DB9 models still common in the UAE. We use genuine or approved OEM-equivalent parts, follow Aston Martin service specifications precisely, and maintain full service records for every visit. For Aston Martin owners who want dealer-quality care without the extended wait times and premium pricing of the franchised network, FixHive offers a genuine alternative in Dubai."
    )
    issues = @(
      @{ title = "V8 AMG Engine Overheating in Dubai Summer Traffic"; body = "The AMG-derived 4.0-litre twin-turbocharged V8 fitted to the DB11, Vantage, DBS and DBX is an extraordinarily capable engine, but its high specific output means it generates substantial heat even at moderate loads. In Dubai summer traffic — where ambient temperatures regularly exceed 45°C and cars sit idling for extended periods — the cooling system operates at or near its design maximum. The twin turbines add significant heat soak to the engine bay, and the inter-cooler circuit must reject additional heat on top of the primary coolant loop. Symptoms of cooling stress include the temperature gauge sitting higher than usual in slow traffic, occasional cooling fan running after engine shutdown, and in advanced cases an overheating warning. We recommend coolant inspection and replacement every 2 years, a thermostat test at every major service, and ensuring the front splitter and undertray are intact to preserve designed airflow." },
      @{ title = "Transmission Software and Adaptive Suspension Calibration"; body = "Aston Martin's ZF-derived 8-speed and 9-speed automatic transmissions contain manufacturer-specific calibration software that controls shift mapping, torque converter lockup and launch control. This software is not accessible via standard OBD-II diagnostic tools — it requires Aston Martin's proprietary diagnostic system or compatible specialist equipment. In Dubai, the transmission faces additional stress from high ambient temperatures and the aggressive driving styles common on UAE highways. Adaptive damper systems — standard on DBX and optional on DB11 — also require periodic recalibration checks, particularly after suspension work. At FixHive we carry specialist diagnostic capability for AMG-platform Aston Martins and can read, clear and log manufacturer-specific fault codes across all control modules." },
      @{ title = "Paint, PPF and Exterior Finish Degradation in UAE Climate"; body = "Aston Martin's paint finishes are among the most complex and expensive in the automotive industry. Many models leave the factory with up to 12 layers of paint applied by hand, and special finishes — Satin, Brushed Aluminium, Carbon Black — require specialist care that is entirely different from standard automotive paintwork. In Dubai, UV radiation at ground level is among the highest in the world, and extended exposure without paint protection film or ceramic coating causes irreversible fading and oxidisation of even the deepest metallic finishes. The front bumper, bonnet and door edges are also vulnerable to stone chips on UAE highways, where road debris and truck tyre fragments are a constant hazard. We strongly recommend full-vehicle PPF installation for all Aston Martin models driven in Dubai, along with an annual ceramic coating maintenance regime." },
      @{ title = "Brake System Wear on High-Performance Variants"; body = "The carbon-ceramic brake option fitted to Vantage AMR, DBS Superleggera and performance-specification DB11 models is a high-temperature braking system designed for track use, but owners in Dubai frequently use these cars on extended motorway journeys and in hot urban traffic. Carbon-ceramic discs are brittle at low temperatures — they perform best above 200°C — and in normal Dubai city driving they may never reach operating temperature, causing micro-cracking of the disc surface over time. Standard cast-iron brake systems on entry Vantage and DBX models wear faster in Dubai due to the sand and dust that acts as an abrasive on pad faces and disc surfaces. Brake fluid absorbs moisture over time, lowering its boiling point — a critical safety issue on a car capable of 300+ km/h. We recommend brake fluid replacement every 2 years on all Aston Martin models." }
    )
    faqs = @(
      @{ q = "How much does Aston Martin servicing cost in Dubai?"; a = "Minor Aston Martin services at FixHive — oil and filter change, multi-point inspection, fluid top-up — start from AED 800–1,200 depending on the model. Major services covering transmission fluid, coolant renewal, brake inspection and spark plug replacement typically range from AED 2,500–5,000. We provide a full written estimate before any work begins, and all pricing is transparent with no hidden charges." },
      @{ q = "Does FixHive have diagnostic equipment for Aston Martin cars?"; a = "Yes. Our workshop carries specialist diagnostic capability compatible with AMG-platform Aston Martin models including the DB11, Vantage, DBX and DBS. We can read and clear manufacturer-specific fault codes across all modules including the engine, transmission, adaptive suspension, stability control and infotainment systems. Pre-2018 V8 Vantage and DB9 models are also supported via compatible legacy diagnostic tools." },
      @{ q = "Is it safe to service my Aston Martin at an independent garage in Dubai?"; a = "Yes, provided the garage uses correct Aston Martin-specified fluids and OEM-equivalent parts, and follows factory service procedures. Under UAE consumer protection regulations you are not required to use a franchised dealer for scheduled maintenance, and doing so will not void your manufacturer warranty provided proper service records are maintained. FixHive issues a full itemised invoice and service record for every visit." },
      @{ q = "How often should I service an Aston Martin driven in Dubai?"; a = "Aston Martin recommends annual services or every 10,000 miles — we recommend 12-month or 15,000 km intervals in UAE conditions given the heat stress on lubricants. Brake fluid should be renewed every 2 years. Coolant should be inspected annually and replaced every 2 years. The DBX requires a more comprehensive 40,000 km service covering differential and transfer fluid in addition to standard items." },
      @{ q = "What PPF and paint protection do you recommend for Aston Martin in Dubai?"; a = "We recommend full-vehicle paint protection film (PPF) for all Aston Martin models in Dubai, ideally applied before the first highway journey. The UAE's dust, sand, road debris and UV levels are extremely damaging to factory paint finishes. For cars already on the road, a professional decontamination, paint correction if needed, and ceramic coating application is the minimum we recommend. Our detailing team has experience with Aston Martin's hand-painted finishes and specialist colour codes." }
    )
    ctaHeading = "Book Your Aston Martin Service in Dubai Today"
    ctaSubtext = "Specialist care for hand-built British grand tourers — precision servicing at independent prices."
    waMsg = "Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20an%20Aston%20Martin%20service"
    alsoLinks = @("bmw-repair-dubai.html","mercedes-benz-repair-dubai.html","audi-repair-dubai.html","porsche-repair-dubai.html","land-rover-repair-dubai.html","jaguar-repair-dubai.html","toyota-repair-dubai.html","honda-repair-dubai.html")
    alsoNames = @("BMW","Mercedes-Benz","Audi","Porsche","Land Rover","Jaguar","Toyota","Honda")
    # AR content
    arTitle = "إصلاح أستون مارتن في دبي | DB11 · Vantage · DBX | فيكس هايف"
    arDesc = "متخصصون في إصلاح وصيانة أستون مارتن في دبي. DB11 وVantage وDBX وDBS. فيكس هايف، مدينة دبي للاستثمار."
    arH1 = "إصلاح وصيانة Aston Martin في دبي"
    arHeroSub = "متخصصون في أستون مارتن DB11 وVantage وDBX وDBS في دبي. السيارات البريطانية المصنوعة يدوياً تستحق رعاية خبراء متخصصين."
    arSpecialty = "DB11 · Vantage · DBX · DBS · Vanquish"
    arIntro = @(
      "تحتل أستون مارتن مكانة استثنائية في عالم السيارات كصانع بريطاني مستقل يُنتج سيارات سياحة رياضية يدوية الصنع تجمع بين الأداء الاستثنائي والأناقة الفريدة. في دبي، تُعدّ أستون مارتن تعبيراً عن الذوق الرفيع، ويتوقع أصحابها أداءً لا تشوبه شائبة في مناخ لم يكن ضمن المعطيات الأصلية للهندسة البريطانية. وقد وسّعت سيارة DBX — أول سيارة SUV من أستون مارتن — حضور الماركة بشكل ملحوظ في سوق الإمارات.",
      "كل سيارة أستون مارتن تعمل بمحرك V8 مشتق من AMG أو V12 مزدوج التوربو مُجمَّع يدوياً. هذه المحركات مُعايَرة للأداء والرقي قبل أي اعتبار آخر، وتتطلب زيوتاً وسوائل وفترات صيانة تعكس هذه الأولوية. في درجات حرارة دبي التي تتجاوز 45°C، تكون متطلبات التبريد والتزليق لهذه المحركات العالية الأداء بالغة القسوة.",
      "تستخدم DBX محرك V8 رباعي التوربو سعة 4.0 لتر مقترناً بناقل حركة أوتوماتيكي تسع سرعات. أما السيارات الرياضية كـDB11 وVantage وDBS فتعمل بحرارة أعلى وتُعرّض أنظمة تبريدها لضغط كبير في ازدحام الصيف. في فيكس هايف نتابع جودة سائل التبريد وحالة الثيرموستات ونزاهة المشعات بوصفها بنوداً أمنية حرجة.",
      "يمتلك فريقنا خبرة بمنصات أستون مارتن المشتقة من AMG إضافة إلى موديلات V8 Vantage وDB9 الأقدم الشائعة في الإمارات. نستخدم قطعاً أصلية أو معادلة معتمدة ونتبع مواصفات الصيانة بدقة مع الاحتفاظ بسجلات كاملة عن كل زيارة."
    )
    arIssues = @(
      @{ title = "⚠️ ارتفاع حرارة محرك V8 AMG في ازدحام دبي الصيفي"; body = "محرك الـ4.0 لتر المزدوج التوربو المشتق من AMG في DB11 وVantage وDBS وDBX يُولّد حرارة هائلة حتى عند أحمال متوسطة. في ازدحام دبي الصيفي تعمل دائرة التبريد عند حدودها القصوى. توصي فيكس هايف باستبدال سائل التبريد كل سنتين واختبار الثيرموستات عند كل صيانة رئيسية." },
      @{ title = "⚠️ معايرة برامج ناقل الحركة والتعليق التكيفي"; body = "تحتوي ناقلات الحركة الأوتوماتيكية في أستون مارتن على برامج معايرة خاصة بالشركة لا يمكن الوصول إليها عبر أدوات OBD-II القياسية. تتطلب أنظمة التعليق التكيفي أيضاً فحصاً دورياً لإعادة المعايرة. تمتلك فيكس هايف أدوات تشخيص متخصصة لمنصات أستون مارتن المشتقة من AMG." },
      @{ title = "⚠️ تدهور الطلاء وحماية الهيكل في مناخ الإمارات"; body = "طلاء أستون مارتن من أكثر الطلاءات تعقيداً وتكلفة في صناعة السيارات. في دبي، تُسبب الأشعة فوق البنفسجية الشديدة تلاشي الألوان وأكسدة الطلاء دون حماية مناسبة. نوصي بتركيب أغشية PPF كاملة لجميع سيارات أستون مارتن المستخدمة في دبي." },
      @{ title = "⚠️ تآكل منظومة الفرامل في الموديلات العالية الأداء"; body = "تتعرض الفرامل الكربونية السيراميكية للتشقق الدقيق عند درجات الحرارة المنخفضة في قيادة المدينة. أما الفرامل الحديدية القياسية فتتآكل بسرعة بسبب الرمال والغبار في دبي. يجب تجديد سائل الفرامل كل سنتين على الأقل للحفاظ على نقطة غليان آمنة." }
    )
    arFaqs = @(
      @{ q = "كم تكلفة صيانة أستون مارتن في دبي؟"; a = "تبدأ الصيانة الخفيفة في فيكس هايف من 800 إلى 1200 درهم حسب الموديل. الصيانات الشاملة تتراوح بين 2500 و5000 درهم وتشمل سائل ناقل الحركة وسائل التبريد والفرامل وشمعات الإشعال." },
      @{ q = "هل تمتلك فيكس هايف معدات تشخيص لسيارات أستون مارتن؟"; a = "نعم، لدينا أدوات تشخيص متخصصة متوافقة مع منصات أستون مارتن المشتقة من AMG بما في ذلك DB11 وVantage وDBX وDBS، وتشمل قراءة وإلغاء رموز أعطال الشركة الصانعة عبر جميع وحدات التحكم." },
      @{ q = "هل من الآمن صيانة أستون مارتن في ورشة مستقلة بدبي؟"; a = "نعم، شريطة استخدام السوائل والقطع المعتمدة واتباع إجراءات الصيانة من المصنع. وفق أنظمة حماية المستهلك في الإمارات لست ملزماً باللجوء إلى الوكيل لصيانة دورية دون أن يتأثر ضمانك، شريطة الاحتفاظ بسجلات صيانة موثقة." },
      @{ q = "كم مرة يجب صيانة أستون مارتن في دبي؟"; a = "نوصي بصيانة سنوية أو كل 15,000 كم في ظروف الإمارات. يجب تجديد سائل الفرامل كل سنتين وفحص سائل التبريد سنوياً واستبداله كل سنتين." },
      @{ q = "ما حماية الطلاء التي توصون بها لأستون مارتن في دبي؟"; a = "نوصي بتركيب أغشية PPF لكامل الهيكل لجميع سيارات أستون مارتن في دبي قبل أول رحلة طويلة، يُضاف إليها طبقة سيراميك للحماية من الأشعة فوق البنفسجية والرمال." }
    )
    arCtaHeading = "احجز صيانة Aston Martin في دبي اليوم"
    arCtaSubtext = "رعاية متخصصة لسيارات بريطانية مصنوعة يدوياً — بجودة الوكالة وأسعار الورشة المستقلة."
    arAlsoNames = @("BMW","Mercedes-Benz","Audi","Porsche","Land Rover","Jaguar","تويوتا","هوندا")
  },

  @{
    slug = "bentley"
    name = "Bentley"
    models = "Continental GT · Flying Spur · Bentayga · Mulsanne"
    heroSub = "Dubai's specialist for Bentley Continental GT, Flying Spur, Bentayga and Mulsanne. Handcrafted British luxury requires technically exacting care to preserve its performance, finish and residual value."
    intro = @(
      "Bentley represents the pinnacle of British automotive craftsmanship — a marque where every car is assembled by hand in Crewe, England, with an attention to detail that takes weeks to complete on each individual vehicle. In Dubai, Bentley is one of the most visible luxury brands on the road, with the Bentayga SUV particularly popular among UAE buyers who want the brand's extraordinary interior craftsmanship paired with the practicality of a high-riding body. Maintaining a Bentley to the standard its engineering demands requires both the technical expertise to handle its complex systems and the care to preserve its exceptional interior and exterior finishes.",
      "Current Bentley models share much of their underpinning with the Volkswagen Group's highest-tier platforms, with the Continental GT and Flying Spur riding on the MSB platform and using either a 6.0-litre twin-turbocharged W12 or a 4.0-litre twin-turbocharged V8. The Bentayga uses the MLB Evo platform shared with the Audi Q7, Lamborghini Urus and Porsche Cayenne. These platforms are technologically sophisticated — featuring active anti-roll bars, electric rear axle steering, and 48-volt mild-hybrid systems on W12 variants — and require diagnostic equipment that goes well beyond standard OBD-II to properly interrogate.",
      "In Dubai's climate, Bentley's air suspension systems face particular challenges. The Bentayga, Flying Spur and Continental GT all offer air suspension as standard or optional equipment, and Dubai's temperature extremes cause air spring rubber bladders to harden and crack over time, leading to slow leaks that first manifest as a slightly lower ride height on one corner in the morning. This is a known wear item in the UAE market. The W12 engine — a masterpiece of engineering with its 12 cylinders arranged in a W configuration — requires immaculate lubrication to maintain its extraordinarily low noise, vibration and harshness characteristics.",
      "At FixHive, we approach every Bentley service with the reverence the car deserves. Our technicians follow Volkswagen Group service procedures for the underlying platforms and use Bentley-approved fluids and OEM-equivalent parts throughout. We maintain full service documentation and can carry out the complete scheduled maintenance programme — including software updates via our VW Group diagnostic tools — so that your Bentley's service history remains comprehensive and verifiable for future resale."
    )
    issues = @(
      @{ title = "W12 Engine Lubrication and Timing Chain Wear"; body = "Bentley's 6.0-litre W12 engine is an engineering marvel — twelve cylinders arranged in a W configuration, twin-turbocharged, producing up to 635 hp in the Speed specification. Its complexity is matched by its sensitivity to lubrication quality. The W12 uses a timing chain system rather than a belt, but the chains require precise oil pressure and viscosity to maintain correct camshaft timing across all four banks. In Dubai, where engine oil degrades faster due to sustained high ambient temperatures and the frequent cold starts that occur throughout the hot season (air conditioning compressor loads the engine heavily from the first moment of startup), oil change intervals should be shortened from the European 15,000 km recommendation to 10,000 km. Consequences of delayed oil changes on the W12 include stretched timing chains, which produce a distinctive rattling noise at cold startup — a repair that runs to five figures at a Bentley dealer. We recommend Bentley-approved 0W-40 full synthetic oil only, changed every 10,000 km." },
      @{ title = "Air Suspension System Degradation in UAE Temperatures"; body = "The air suspension systems fitted to the Bentayga, Flying Spur and Continental GT are central to the Bentley driving experience — providing the extraordinary combination of ultra-supple ride quality and razor-sharp handling that defines the marque. These systems use rubberised air spring bladders inflated to precise pressures, and Dubai's temperature extremes are particularly aggressive on rubber components. The repeated thermal cycling between 15°C air-conditioned interiors and 50°C exterior temperatures causes the rubber bladder material to harden and develop micro-cracks over several years. The first symptom is typically a slow air leak that causes one corner to sit lower than the others overnight. If left unaddressed, a complete bladder failure at speed can cause the car to suddenly drop onto its bump stops, which is both alarming and potentially dangerous. We inspect air suspension pressure and bladder condition at every major service, and we carry replacement air spring assemblies for common Bentley models." },
      @{ title = "Bentley Interior and Exterior Finish Maintenance in Dubai"; body = "A Bentley's interior is among the most labour-intensive in the automotive world. Hand-stitched leather hides, polished veneer panels, chrome and brushed aluminium trim — each element requires specialist care to maintain its condition in Dubai's environment. The combination of extreme UV levels, fine desert dust, and the humidity spikes of Dubai's brief wet season are particularly destructive. Leather surfaces exposed to direct sunlight through the panoramic glass roof bleach and crack without regular conditioning with Bentley-approved leather care products. Wood veneer and piano black trim panels develop micro-scratches from dust particles during cleaning if incorrect products or cloths are used. Exterior chrome work pits and tarnishes without regular protection. Our detailing team understands Bentley-specific finishes and carries the correct care products for each surface." },
      @{ title = "DCT Dual-Clutch Transmission Hesitation in City Traffic"; body = "The dual-clutch transmission fitted to the Continental GT and Flying Spur — an 8-speed DCT unit developed in conjunction with ZF — is calibrated for smooth, rapid shifts at medium to high speeds. In Dubai's stop-start city traffic, the transmission spends extended periods operating in the low-speed, high-slip zone where the dual clutch packs generate heat without full engagement. Over time, and particularly when the transmission fluid is approaching service age, this results in a characteristic jerkiness or hesitation when pulling away from a standstill or manoeuvring at parking speeds. DCT fluid degradation also accelerates in high ambient temperatures. We recommend transmission fluid replacement every 40,000 km for UAE-driven Continental GT and Flying Spur models, rather than Bentley's global recommendation which does not fully account for UAE traffic conditions." }
    )
    faqs = @(
      @{ q = "How much does Bentley servicing cost in Dubai?"; a = "Minor Bentley services at FixHive — oil and filter change, fluid top-ups, multi-point inspection — start from AED 1,200–2,000 depending on model and engine. W12 models require approximately double the oil volume of a V8, which is reflected in the cost. Major services covering transmission fluid, coolant, spark plugs, air filter and brake inspection typically run AED 4,000–8,000. All costs are confirmed in writing before work begins." },
      @{ q = "How often should I change the oil in my Bentley W12 in Dubai?"; a = "We recommend W12 oil changes every 10,000 km in UAE conditions rather than the European 15,000 km interval. Dubai's sustained high ambient temperatures and frequent cold-start air-conditioning loads degrade synthetic lubricants faster than in temperate climates. Maintaining the correct oil change interval is the single most important thing you can do to protect the W12's timing chain system and ensure its legendary low NVH levels are preserved." },
      @{ q = "Does FixHive have diagnostic tools for Bentley vehicles?"; a = "Yes. Bentley models from 2003 onwards use Volkswagen Group electronic architectures that our VW Group diagnostic tools fully support. This includes the Continental GT (W12 and V8), Flying Spur, and Bentayga. We can read, log and clear fault codes across all modules including the W12 engine management, dual-clutch transmission, air suspension control unit, active anti-roll bars, and infotainment system." },
      @{ q = "Is it safe to service my Bentley at an independent garage in Dubai?"; a = "Yes. UAE consumer protection regulations permit you to have your Bentley maintained at any qualified independent garage without voiding the manufacturer warranty, provided correct fluids, OEM-equivalent parts and factory procedures are used. FixHive issues a full itemised service record for every visit. Many long-term Bentley owners in Dubai use FixHive as their primary service partner due to our faster turnaround times and transparent pricing." },
      @{ q = "What PPF and paint protection do you recommend for Bentley in Dubai?"; a = "Full-vehicle paint protection film is our minimum recommendation for Bentley in Dubai. The Crewe-manufactured paint finishes are exceptional but vulnerable to the UAE's UV levels, road debris and fine dust. For cars with special finishes — Satin, Two-Tone, Carbon Fibre — full PPF is non-negotiable to preserve both appearance and resale value. We also recommend an annual interior leather conditioning treatment and UV-protective window tinting to protect the handstitched interior." }
    )
    ctaHeading = "Book Your Bentley Service in Dubai Today"
    ctaSubtext = "W12 and V8 specialist care — preserving Crewe craftsmanship in Dubai's climate."
    waMsg = "Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20Bentley%20service"
    alsoLinks = @("rolls-royce-repair-dubai.html","mercedes-benz-repair-dubai.html","bmw-repair-dubai.html","audi-repair-dubai.html","porsche-repair-dubai.html","land-rover-repair-dubai.html","toyota-repair-dubai.html","lexus-repair-dubai.html")
    alsoNames = @("Rolls-Royce","Mercedes-Benz","BMW","Audi","Porsche","Land Rover","Toyota","Lexus")
    arTitle = "إصلاح بنتلي في دبي | Continental GT · Flying Spur · Bentayga | فيكس هايف"
    arDesc = "متخصصون في إصلاح بنتلي في دبي. Continental GT وFlying Spur وBentayga وMulsanne. رعاية متخصصة بمعايير الوكالة."
    arH1 = "إصلاح وصيانة Bentley في دبي"
    arHeroSub = "متخصصون في بنتلي Continental GT وFlying Spur وBentayga وMulsanne في دبي. الفخامة البريطانية المصنوعة يدوياً تستحق رعاية تقنية على أعلى مستوى."
    arSpecialty = "Continental GT · Flying Spur · Bentayga · Mulsanne"
    arIntro = @(
      "تمثل بنتلي قمة الحرفية البريطانية في صناعة السيارات — كل سيارة تُجمَّع يدوياً في كرو بإنجلترا باهتمام بالتفاصيل يستغرق أسابيع لكل مركبة على حدة. في دبي، تُعدّ بنتلي من أكثر ماركات الفخامة حضوراً على الطرق، لا سيما سيارة Bentayga التي تحظى بشعبية كبيرة في الإمارات.",
      "تشترك موديلات بنتلي الحالية مع منصات فولكسفاغن العليا. تستخدم Continental GT وFlying Spur منصة MSB بمحرك W12 أو V8 مزدوج التوربو، فيما تقوم Bentayga على منصة MLB Evo المشتركة مع Audi Q7 وPorsche Cayenne. هذه المنصات متطورة للغاية وتتطلب معدات تشخيص تفوق قدرات OBD-II القياسية بكثير.",
      "في مناخ دبي تواجه أنظمة التعليق الهوائي لبنتلي تحديات بالغة. التقلبات الحرارية المتكررة تُسبب تصلب وتشقق أكياس الهواء المطاطية مما يؤدي إلى تسريب بطيء يظهر في صورة انخفاض طفيف في ارتفاع إحدى زوايا الهيكل صباحاً. نفحص حالة التعليق الهوائي عند كل صيانة رئيسية.",
      "في فيكس هايف نتعامل مع كل سيارة بنتلي بالاحترام الذي تستحقه. نتبع إجراءات صيانة مجموعة فولكسفاغن للمنصات الأساسية ونستخدم سوائل معتمدة من بنتلي وقطعاً معادلة OEM مع الحفاظ بسجلات صيانة كاملة وقابلة للتحقق."
    )
    arIssues = @(
      @{ title = "⚠️ تزليق محرك W12 وتآكل سلسلة التوقيت"; body = "محرك W12 الـ6.0 لتر ذو الاثني عشر أسطوانة يتطلب تزليقاً دقيقاً. في دبي، تتدهور جودة الزيت بسرعة بسبب الحرارة الشديدة وأحمال ضاغط التكييف. نوصي بتغيير الزيت كل 10,000 كم بزيت تخليقي 0W-40 معتمد من بنتلي لتفادي امتداد سلسلة التوقيت." },
      @{ title = "⚠️ تدهور منظومة التعليق الهوائي في حرارة الإمارات"; body = "أنظمة التعليق الهوائي في Bentayga وFlying Spur وContinental GT حساسة للتقلبات الحرارية. يتسبب التدوير الحراري المتكرر بين البيئة الداخلية المكيفة والحرارة الخارجية في تصلب وتشقق أكياس الهواء المطاطية. نفحص ضغط الهواء وحالة الأكياس عند كل صيانة." },
      @{ title = "⚠️ صيانة التشطيبات الداخلية والخارجية الفاخرة في دبي"; body = "يتطلب الجلد المخيط يدوياً والخشب المصقول والزجاج والألومنيوم المصقول رعاية متخصصة. الأشعة فوق البنفسجية الشديدة والغبار في دبي تُلحق ضرراً بالغاً بدون منتجات العناية المعتمدة. فريق التلميع في فيكس هايف يحمل المنتجات الصحيحة لكل سطح من أسطح بنتلي." },
      @{ title = "⚠️ تردد ناقل DCT في ازدحام المدينة"; body = "ناقل الحركة ذو القابضين المزدوجين في Continental GT وFlying Spur مُعايَر للتسارع السريع على السرعات المتوسطة والعالية. في ازدحام دبي يُقضي وقتاً طويلاً في منطقة الانزلاق المنخفض مما يُسبب تدهوراً في سائل ناقل الحركة وتذبذباً ملحوظاً. نوصي بتغيير سائل DCT كل 40,000 كم." }
    )
    arFaqs = @(
      @{ q = "كم تكلفة صيانة بنتلي في دبي؟"; a = "تبدأ الصيانة الخفيفة من 1200 إلى 2000 درهم حسب الموديل والمحرك. الصيانة الشاملة تتراوح بين 4000 و8000 درهم وتشمل سائل ناقل الحركة وسائل التبريد وشمعات الإشعال." },
      @{ q = "كم مرة يجب تغيير زيت محرك W12 في دبي؟"; a = "نوصي بتغيير الزيت كل 10,000 كم في الإمارات بدلاً من الفاصل الأوروبي 15,000 كم. حرارة دبي الشديدة تُسرّع تدهور الزيت التخليقي مما قد يُلحق ضرراً بسلسلة التوقيت." },
      @{ q = "هل تمتلك فيكس هايف أدوات تشخيص لسيارات بنتلي؟"; a = "نعم. تستخدم موديلات بنتلي معمارية إلكترونية من مجموعة فولكسفاغن يدعمها الكامل أدوات التشخيص لدينا، بما في ذلك W12 وV8 وناقل الحركة والتعليق الهوائي." },
      @{ q = "هل من الآمن صيانة بنتلي في ورشة مستقلة بدبي؟"; a = "نعم. تنظيمات حماية المستهلك في الإمارات تتيح ذلك دون المساس بالضمان شريطة استخدام القطع والسوائل الصحيحة. فيكس هايف تُصدر سجل صيانة كاملاً ومفصّلاً لكل زيارة." },
      @{ q = "ما حماية الطلاء التي توصون بها لبنتلي في دبي؟"; a = "نوصي بأغشية PPF لكامل الهيكل كحد أدنى. للتشطيبات الخاصة كالساتان أو اللونين أو الكربون الليفي، تُعدّ الحماية الكاملة أمراً لا غنى عنه للحفاظ على المظهر وقيمة إعادة البيع." }
    )
    arCtaHeading = "احجز صيانة Bentley في دبي اليوم"
    arCtaSubtext = "رعاية متخصصة لمحرك W12 والتعليق الهوائي — بجودة الوكالة وأسعار الورشة المستقلة."
    arAlsoNames = @("Rolls-Royce","Mercedes-Benz","BMW","Audi","Porsche","Land Rover","تويوتا","لكزس")
  },

  @{
    slug = "byd"
    name = "BYD"
    models = "Atto 3 · Seal · Han · Tang · Dolphin · Sealion"
    heroSub = "Dubai's specialist for BYD electric and plug-in hybrid vehicles. Atto 3, Seal, Han, Tang and Dolphin — advanced EV diagnostics, battery health checks and OTA software support in Dubai."
    intro = @(
      "BYD — Build Your Dreams — has emerged as one of the most significant automotive forces of the 2020s, overtaking Tesla globally in terms of total EV and PHEV sales volume. In the UAE, BYD has established a strong and rapidly growing presence, with the Atto 3 electric SUV becoming one of the best-selling electric vehicles in the country. The brand's combination of competitive pricing, impressive real-world range, and advanced battery technology has made it a genuine mainstream choice rather than a niche curiosity. As BYD's UAE fleet grows, so does the need for technically capable independent service centres that understand the brand's technology.",
      "BYD is unique among automakers in that it manufactures its own battery cells, electric motors, power electronics and vehicle control software — a level of vertical integration that gives it extraordinary control over its product but also creates a more complex service environment. The BYD Blade Battery technology used across the Atto 3, Seal, Han and Dolphin is a lithium iron phosphate (LFP) chemistry in a novel cell-to-pack format that eliminates traditional modules. LFP chemistry is extremely stable and thermally safe — it does not suffer from the thermal runaway risks associated with NMC batteries — but it has different management characteristics that require correct BMS calibration.",
      "In Dubai's climate, BYD electric vehicles face specific challenges around thermal management. The battery pack must be maintained within a precise temperature window for optimal charging speed, range and longevity. BYD's active liquid cooling system handles this effectively, but the cooling fluid requires inspection and replacement on schedule. Importantly, the efficiency penalty of running the cabin air conditioning in Dubai's heat can reduce real-world range by 25-35% compared to European rated figures — a normal and expected characteristic of all EVs in hot climates, not a fault. However, if the battery thermal management system is not functioning correctly, range degradation can be significantly worse.",
      "BYD vehicles also receive over-the-air (OTA) software updates that can modify range, charging curves, regenerative braking behaviour and driver assistance features. At FixHive, our technicians stay current with BYD's software versions and can advise owners on which updates are recommended and which are optional. We carry diagnostic capability for BYD's DiLink infotainment architecture and the underlying vehicle control systems. Our workshop is also equipped to perform AC charging equipment checks and can diagnose DC fast charging communication faults that sometimes arise with third-party chargers in the UAE."
    )
    issues = @(
      @{ title = "Battery Range Degradation and Thermal Management in Dubai Heat"; body = "The BYD Blade Battery is a lithium iron phosphate chemistry known for exceptional cycle life and thermal stability, but all EV batteries lose capacity over time, and Dubai's climate accelerates this process if the thermal management system is not operating correctly. In normal operation, BYD's active liquid cooling maintains battery temperature between 20°C and 40°C even in 50°C ambient heat during fast charging. However, if the cooling circuit develops a blockage, loses fluid, or if the chiller system that pre-cools the battery during DC charging loses performance, battery temperatures can rise above the optimal window. Chronic elevated temperature accelerates LFP capacity fade, and owners may notice gradually increasing charge times and decreasing range. We recommend annual battery health checks at FixHive to baseline capacity, check cooling circuit integrity, inspect the battery management software version, and identify any latent fault codes that have not yet triggered a dashboard warning." },
      @{ title = "Charging System Issues with UAE Third-Party Chargers"; body = "BYD vehicles sold in the UAE use the CCS2 charging standard for DC fast charging and a Type 2 AC connector for home and destination charging. Compatibility issues arise frequently with some UAE-installed DC fast chargers, particularly older OCPP 1.5 protocol chargers at petrol station forecourts and some mall car parks. These incompatibilities typically manifest as a session failing to start, a charge session terminating early at a low state of charge, or the car refusing to communicate with the charger. These are rarely hardware faults — more often they reflect a charger firmware mismatch or a vehicle software version issue. BYD periodically releases charging compatibility updates via OTA. At FixHive we can check and update your vehicle's charging firmware and log diagnostic data from the onboard charging computer to identify persistent compatibility issues." },
      @{ title = "DiLink Infotainment System Freezing and Connectivity Faults"; body = "BYD's DiLink 4.0 and DiLink 100 infotainment systems — both Android-based platforms with rotating landscape-to-portrait screens — are advanced and feature-rich, but early software versions had known stability issues including random screen freezes, app crashes, slow response times, and Bluetooth connectivity problems. Many of these issues were resolved in subsequent OTA updates. In the UAE, owners of Atto 3 models that did not receive automatic updates due to SIM card or connectivity issues may still be running older software versions. Additionally, the USB-C charging ports in the DiLink ecosystem can develop intermittent connectivity issues when exposed to high humidity and dust — a minor but recurring complaint among Dubai owners. We carry the latest BYD software update files and can perform wired updates for vehicles with OTA reception problems." },
      @{ title = "AC Motor and Power Electronics Heat Soak"; body = "BYD's permanent magnet synchronous motors are highly efficient, but efficiency is not 100% — the lost energy is dissipated as heat in the motor stator, rotor and power electronics. In Dubai, where ambient temperatures are already extreme, the thermal headroom for these components is reduced. Extended high-speed driving on the E11 between Dubai and Abu Dhabi at 120 km/h in 45°C heat can cause some BYD models to reduce peak power output as a protective thermal measure — a behaviour known as thermal derating. This is normal and does not indicate a fault, but if power derating occurs at moderate speeds or in relatively mild conditions, it may indicate that the motor cooling circuit is restricted, the inverter cooling plate has a blockage, or the cooling fan is not functioning correctly. We inspect the complete e-drive thermal circuit at every BYD service." }
    )
    faqs = @(
      @{ q = "How much does BYD servicing cost in Dubai?"; a = "BYD electric vehicles require less routine maintenance than ICE cars — no oil changes, no spark plugs, no timing belts. A standard annual BYD service at FixHive typically costs AED 400–700, covering brake fluid, cabin air filter, wiper blades, tyre rotation, battery health check and a full software and fault code scan. Brake pad replacement is rarely needed due to regenerative braking, and when it is required, it is straightforward and cost-effective." },
      @{ q = "How often should I get my BYD battery health checked in Dubai?"; a = "We recommend an annual battery health check for all BYD EVs driven in Dubai. The check takes approximately 45 minutes and involves logging the battery management system data, checking cell voltage balance, measuring available capacity against original specification, inspecting the thermal management cooling circuit, and verifying that the battery software is on the latest version. Early detection of cell imbalance or cooling inefficiency can prevent accelerated capacity degradation." },
      @{ q = "Does FixHive support BYD OTA updates?"; a = "FixHive stays current with BYD's software release schedule and can perform wired software updates for vehicles that have difficulty receiving OTA updates automatically. We can also advise on which updates are recommended for UAE conditions, check that updates have applied correctly, and restore previous software versions in the rare cases where an update causes a regression." },
      @{ q = "Why is my BYD Atto 3 range lower than the rated figure in Dubai?"; a = "A range reduction of 25–35% versus the WLTP rated figure is entirely normal in Dubai and does not indicate a battery problem. The primary cause is the air conditioning load — running full AC in 45°C heat consumes 2–4 kW continuously. Motorway driving at UAE speed limits (100–130 km/h) also consumes significantly more energy than the mixed-speed test cycle. If your real-world range has declined noticeably compared to your own previous experience — rather than the rated figure — a battery health check is recommended." },
      @{ q = "Can FixHive service my BYD under warranty?"; a = "Yes. UAE consumer protection regulations permit independent garages to perform warranty-compliant scheduled maintenance, provided correct procedures, fluids and OEM-equivalent parts are used. We issue a full service record for every visit. For warranty claims or recall work, the BYD authorised dealer network must be used, but all scheduled servicing can be performed at FixHive without affecting your warranty entitlement." }
    )
    ctaHeading = "Book Your BYD Service in Dubai Today"
    ctaSubtext = "EV-specialist care for BYD Blade Battery vehicles — battery health checks, software updates and complete EV servicing."
    waMsg = "Hey%2C%20I%20saw%20your%20website%2C%20I%20wanted%20to%20book%20a%20BYD%20service"
    alsoLinks = @("tesla-repair-dubai.html","hyundai-repair-dubai.html","kia-repair-dubai.html","toyota-repair-dubai.html","honda-repair-dubai.html","nissan-repair-dubai.html","bmw-repair-dubai.html","mercedes-benz-repair-dubai.html")
    alsoNames = @("Tesla","Hyundai","Kia","Toyota","Honda","Nissan","BMW","Mercedes-Benz")
    arTitle = "إصلاح BYD في دبي | Atto 3 · Seal · Han | فيكس هايف"
    arDesc = "متخصصون في إصلاح وصيانة BYD الكهربائية وهجينة القابس في دبي. Atto 3 وSeal وHan وDolphin. فيكس هايف."
    arH1 = "إصلاح وصيانة BYD في دبي"
    arHeroSub = "متخصصون في سيارات BYD الكهربائية وهجينة القابس في دبي — Atto 3 وSeal وHan وDolphin. فحص صحة البطارية وتحديثات البرامج."
    arSpecialty = "Atto 3 · Seal · Han · Tang · Dolphin"
    arIntro = @(
      "برزت BYD — اختصار لـ Build Your Dreams — كواحدة من أبرز قوى صناعة السيارات في العقد الثالث من الألفية الثالثة، متجاوزةً تسلا عالمياً من حيث إجمالي مبيعات السيارات الكهربائية وهجينة القابس. في الإمارات، رسّخت BYD حضوراً قوياً ومتنامياً بسرعة، إذ باتت Atto 3 من أكثر السيارات الكهربائية مبيعاً في البلاد.",
      "تتميز BYD بأنها تُصنّع خلايا البطاريات والمحركات الكهربائية والإلكترونيات والبرامج بنفسها — مستوى من التكامل الرأسي يمنحها تحكماً استثنائياً في منتجها. تقنية Blade Battery المستخدمة في Atto 3 وSeal وHan تعتمد على كيمياء فوسفات الحديد الليثيومي في تصميم cell-to-pack الذي يلغي الوحدات التقليدية.",
      "في مناخ دبي، تواجه سيارات BYD الكهربائية تحديات خاصة بإدارة الحرارة. يتطلب حزمة البطارية الحفاظ على نطاق حرارة دقيق لتسريع الشحن الأمثل والمدى والعمر الافتراضي. كما أن خسارة الكفاءة جراء تشغيل مكيف الهواء في حرارة دبي قد تُخفض المدى الفعلي بنسبة 25-35% مقارنة بالأرقام الأوروبية.",
      "تتلقى سيارات BYD أيضاً تحديثات برامج OTA يمكن أن تُعدّل منحنيات الشحن وسلوك الفرملة الاسترجاعية وميزات مساعدة السائق. في فيكس هايف يواكب فريقنا إصدارات برامج BYD ونمتلك قدرات تشخيصية لمعمارية DiLink والأنظمة الأساسية."
    )
    arIssues = @(
      @{ title = "⚠️ تراجع مدى البطارية وإدارة الحرارة في حر دبي"; body = "بطارية BYD Blade من نوع LFP معروفة بثباتها الحراري واستقرارها، لكن الحرارة المرتفعة تُسرّع تدهور الطاقة إذا لم تعمل دائرة التبريد بكفاءة. نوصي بفحص سنوي لصحة البطارية يشمل قياس السعة المتاحة وفحص دائرة التبريد والتحقق من إصدار برنامج BMS." },
      @{ title = "⚠️ مشاكل شحن مع محطات الجهة الثالثة في الإمارات"; body = "تستخدم سيارات BYD في الإمارات معيار CCS2 للشحن السريع. تنشأ مشاكل التوافق مع بعض محطات الشحن القديمة في الدولة وتظهر في صورة فشل في بدء الجلسة أو انقطاع مبكر. في الغالب تعكس هذه المشاكل عدم تطابق إصدارات البرامج وليست أعطالاً في الأجهزة." },
      @{ title = "⚠️ تجمد نظام DiLink وأعطال الاتصال"; body = "أنظمة DiLink 4.0 قد تعاني من تجمد الشاشة وبطء الاستجابة ومشاكل البلوتوث في الإصدارات القديمة. كثير من هذه المشاكل تم حلها في تحديثات OTA اللاحقة. نحمل في فيكس هايف أحدث ملفات تحديث BYD ونُجري التحديثات السلكية للسيارات التي تواجه صعوبة في التحديث التلقائي." },
      @{ title = "⚠️ تقليل طاقة المحرك الكهربائي بسبب الحرارة في السرعات العالية"; body = "تُشعّ محركات BYD الكهربائية حرارة تُقلّص الهامش الحراري المتاح في الأجواء الحارة. قيادة السرعة العالية المطوّلة على الطريق السريع في درجات 45°C قد تُسبب تقليل الطاقة كإجراء وقائي. إذا ظهر هذا التقليل في ظروف عادية، فقد يشير إلى انسداد في دائرة تبريد المحرك." }
    )
    arFaqs = @(
      @{ q = "كم تكلفة صيانة BYD في دبي؟"; a = "السيارات الكهربائية BYD تتطلب صيانة روتينية أقل بكثير من المحركات الحرارية. تكلف الصيانة السنوية في فيكس هايف عادةً 400 إلى 700 درهم وتشمل سائل الفرامل وفلتر الهواء والمساحات وتدوير الإطارات وفحص صحة البطارية." },
      @{ q = "كم مرة يجب فحص صحة بطارية BYD في دبي؟"; a = "نوصي بفحص سنوي لصحة البطارية يستغرق 45 دقيقة ويشمل تسجيل بيانات BMS وفحص توازن خلايا الجهد وقياس السعة المتاحة وفحص دائرة التبريد والتحقق من إصدار البرنامج." },
      @{ q = "هل تدعم فيكس هايف تحديثات OTA لسيارات BYD؟"; a = "نعم. نواكب جدول إصدارات برامج BYD ونُجري التحديثات السلكية للسيارات التي تواجه مشكلة في التحديث التلقائي، كما نتحقق من صحة تطبيق التحديثات." },
      @{ q = "لماذا مدى Atto 3 أقل من المعدل المُعلَن في دبي؟"; a = "انخفاض المدى بنسبة 25-35% عن قيمة WLTP أمر طبيعي تماماً في دبي، السبب الرئيسي هو حمل مكيف الهواء الذي يستهلك 2-4 كيلوواط باستمرار. إذا انخفض المدى بشكل ملحوظ مقارنةً بتجربتك السابقة الشخصية، يُوصى بفحص البطارية." },
      @{ q = "هل تستطيع فيكس هايف صيانة BYD ضمن الضمان؟"; a = "نعم. تتيح أنظمة حماية المستهلك في الإمارات صيانة السيارة في ورش مستقلة مع الحفاظ على الضمان، شريطة اتباع الإجراءات الصحيحة. نُصدر سجل صيانة كامل لكل زيارة." }
    )
    arCtaHeading = "احجز صيانة BYD في دبي اليوم"
    arCtaSubtext = "رعاية متخصصة لسيارات Blade Battery الكهربائية — فحص صحة البطارية وتحديثات البرامج والصيانة الشاملة."
    arAlsoNames = @("Tesla","هيونداي","كيا","تويوتا","هوندا","نيسان","BMW","Mercedes-Benz")
  }
)

# This script produces the data. The actual file generation is in the next function.
Write-Host "Brand data loaded: $($brands.Count) brands defined so far."
